### ISSUE TITLE
PTQ AdaRound ONNX KeyError

### ISSUE THREAD

**Issue by zhenhouhong** [ModelTC/MQBench#100]
环境：
Ubuntu18.04，cuda10.1，
Torch==1.8.1+cu101, Torchvision==0.9.1+cu101，
onnx==1.11.0，onnx-simplifier==0.3.10，onnxoptimizer==0.2.7，onnxruntime==1.11.1

安装：
使用的MQBench是最新的main分支代码。安装过程是按照文档的说明进行安装。

过程：
我运行imagenet_example中的PTQ Adaround 的例子，使用默认的 r18_2_4.yaml ，运行结果没有问题。

尝试对 resnet50 用adaround 进行 weight 4bit  activation 8 bit 的量化，并且以 onnx_qnn 形式 deploy。
yaml文件是参照 r18_2_4.yaml 以及 r18_8_8_trt.yaml 。
没有对ptq.py 进行修改。

结果：
日志报了 KeyError: reshape_1 的错误。报错来自 advanced_ptq.py的ptq_reconstruction。

![image](https://user-images.githubusercontent.com/86860311/169187758-c9e7202e-6f0b-40c4-9af2-57227fde96b6.png)

**Comment by Tracin** [comment]
非常详细的复现步骤！我们会尽快修复

**Comment by zhenhouhong** [comment]
> 

感谢

**Comment by PannenetsF** [comment]
#125
