### ISSUE TITLE
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

### ISSUE THREAD

**Issue by ayenuaa** [ModelTC/MQBench#101]
你好，我使用AdaRound对实验室的业务模型进行了实操，出现了如下问题：
![image](https://user-images.githubusercontent.com/26295078/169192728-6d3a80a1-bdeb-4976-b246-ee9ed0af1e97.png)
  看起来是不支持nn.linear的后量化吗？

**Comment by Tracin** [comment]
Linear支持的，能复现问题的模型片段可以提供吗

**Comment by ayenuaa** [comment]
查到原因了，网络里有个常量，requires_grad设置为True的话就不报错了。话说常量就必须要参与梯度反向传播吗？有没有其他的处理办法？ @Tracin @un-knight @a1trl9 @thb1314
