### ISSUE TITLE
How to tell if the model is in the state of torch.fx.trace process?

### ISSUE THREAD

**Issue by xingyueye** [ModelTC/MQBench#105]
Hi～ I would like to know if there is a function in torch.fx similar to “torch.jit.is_tracing()” that can be used to tell if a trace is in progress. I need to reform my model definition to match the process of torch.fx.trace, but I am not very familiar with that. Thus a lot of problems encountered, hope to get your help

**Comment by PannenetsF** [comment]
https://github.com/ModelTC/MQBench/blob/main/mqbench/fake_quantize/lsq.py#L67
