### ISSUE TITLE
Per-tensor量化模型参数导出失败，Per-channel没问题

### ISSUE THREAD

**Issue by ayenuaa** [ModelTC/MQBench#108]
我尝试对Resnet18进行Per-tensor和Per-channel后量化，发现Per-tensor量化模型在进行convert_deploy时会报错：
![image](https://user-images.githubusercontent.com/26295078/172514363-9233b77a-7082-4952-872e-efeb5d8d9378.png)

目前报错的阶段我定位在了remove_fakequantize_and_collect_params阶段。

**Comment by Tracin** [comment]
似乎已經fix了
https://github.com/ModelTC/MQBench/commit/67b1d7bcffeae6f8932335e6e2f473227acb3f29
