### ISSUE TITLE
PPLW8A16是什么平台？

### ISSUE THREAD

**Issue by NickYangMin** [ModelTC/MQBench#11]

**Comment by www516717402** [comment]
http://mqbench.tech/assets/docs/html/hardware/ppl_dsp.html

**Comment by XHPlus** [comment]
PPLW8A16 is a quantization implementation on DSP by SenseTime HPC team. For some open-source resources, please refer to https://openppl.ai/home

**Comment by NickYangMin** [comment]
好的，谢谢！

**Comment by NickYangMin** [comment]
ppl转换成onnx时，得到ppl_clip_range.json，里面的weight名称已经和对应的卷积名称已经对不上了，后面你们是怎么用的？
比如resnet18第一层卷积，对应的权重名称conv1.weight，但是conv1已经被改成466这样的数字了。
