### ISSUE TITLE
EntropyCalibratorV2 in tensorrt backend.

### ISSUE THREAD

**Issue by apxlwl** [ModelTC/MQBench#115]
作者好，非常好的工作。关于tensorrt有个初级的问题。
1. 目前支持的naive ptq是否只是trt的MinMaxCalibrator？
2. 更常用的EntropyCalibratorV2是否有计划支持？
3. 项目中的advanced ptq算法是否在trt实际部署的时候会优于EntropyCalibratorV2？
非常感谢！

**Comment by Tracin** [comment]
除Minmax还有一些支持,可以查看observer.py
之前有尝试过Entropy量化,由于效率/精度方面原因没有release,实际上使用Minmax/Hist/MSE就可以达到不错的效果
