### ISSUE TITLE
KeyError for Adaround、Qdrop

### ISSUE THREAD

**Issue by feixiang7701** [ModelTC/MQBench#117]
When I use the MQBench to quant RLFN model with Qdrop、adaround, some errors have occurred.
**env：**
Ubuntu18.04，cuda11.1，
MQbench version: e2175203c8e62596e66500a720a6cb1d1fc1dacd
RLFN is a super resolution model from: https://github.com/ofsoundof/NTIRE2022_ESR, the model id is 4.
![image](https://user-images.githubusercontent.com/17311343/174219876-d00308c3-836c-422d-abca-08708f3c9d3d.png)

**error:**
[MQBENCH] INFO: Disable observer and Disable quantize.
[MQBENCH] INFO: Disable observer and Enable quantize.
[MQBENCH] INFO: prepare layer reconstruction for fea_conv
[MQBENCH] INFO: the node list is below!
[MQBENCH] INFO: [input_1_post_act_fake_quantizer, fea_conv, fea_conv_post_act_fake_quantizer_2]
Traceback (most recent call last):
  File "quant.py", line 158, in <module>
    main()
  File "quant.py", line 137, in main
    model = ptq_reconstruction(model, stacked_tensor, EasyDict(ptq_reconstruction_config))
  File ".../mqbench/advanced_ptq.py", line 636, in ptq_reconstruction
    fp32_module = fp32_modules[qnode2fpnode_dict[layer_node_list[-1]]]
KeyError: fea_conv_post_act_fake_quantizer_2

**Here is my code tracking and analysis**

（1）**mode.code**
def forward(self, input):
    input_1 = input
    input_1_post_act_fake_quantizer = self.input_1_post_act_fake_quantizer(input_1);  input_1 = None
    fea_conv = self.fea_conv(input_1_post_act_fake_quantizer);  input_1_post_act_fake_quantizer = None
    fea_conv_post_act_fake_quantizer_2 = self.fea_conv_post_act_fake_quantizer(fea_conv)
    fea_conv_post_act_fake_quantizer_1 = self.fea_conv_post_act_fake_quantizer(fea_conv)
    fea_conv_post_act_fake_quantizer = self.fea_conv_post_act_fake_quantizer(fea_conv);  fea_conv = None
    ...
（2）"problems"
问题,quant model node.target多对1,导致quant_named_nodes缺少keys：
mqbench/advanced_ptq.py-》qnode2fpnode(quant_modules, fp32_modules):
def qnode2fpnode(quant_modules, fp32_modules):
    quant_named_nodes = {node.target: node for node in quant_modules}
    **"""
    node:fea_conv_post_act_fake_quantizer_2  node.target:fea_conv_post_act_fake_quantizer
    node:fea_conv_post_act_fake_quantizer_1  node.target:fea_conv_post_act_fake_quantizer
    """**
    fp32_named_nodes = {node.target: node for node in fp32_modules}
    qnode2fpnode_dict = {quant_named_nodes[key]: fp32_named_nodes[key] for key in quant_named_nodes}
    return qnode2fpnode_dict

I am not familiar with the process of trained PTQ, so looking forward to your suggestions and Solutions.

**Comment by PannenetsF** [comment]
Thanks for your feedback! 

It could be a bug for `File ".../mqbench/advanced_ptq.py", line 636, in ptq_reconstruction, KeyError: fea_conv_post_act_fake_quantizer_2`, fake quantizer should not be here.

Please provide a re-produceable code for this model, so I can fix it.

**Comment by feixiang7701** [comment]
Here is the code for quant with MQbench, you can download the 'quant_v1.txt' and then rename it as 'quant_v1.py'.
[quant_v1.txt](https://github.com/ModelTC/MQBench/files/8936951/quant_v1.txt)
Please palce the quant_v1.py in [NTIRE2022_ESR](https://github.com/ofsoundof/NTIRE2022_ESR), then run the command:
` python  quant_v1.py 4 --train-dir DIV2K_train_LR_bicubic --val-dir DIV2K_valid_LR_bicubic
`
the DIV2K_train_LR_bicubic  directory structure should like:
DIV2K_train_LR_bicubic/X4/*.png

**Comment by PannenetsF** [comment]
#125

**Comment by PannenetsF** [comment]
> Here is the code for quant with MQbench, you can download the 'quant_v1.txt' and then rename it as 'quant_v1.py'. [quant_v1.txt](https://github.com/ModelTC/MQBench/files/8936951/quant_v1.txt) Please palce the quant_v1.py in [NTIRE2022_ESR](https://github.com/ofsoundof/NTIRE2022_ESR), then run the command: `python quant_v1.py 4 --train-dir DIV2K_train_LR_bicubic --val-dir DIV2K_valid_LR_bicubic` the DIV2K_train_LR_bicubic directory structure should like: DIV2K_train_LR_bicubic/X4/*.png


This error could not be reproduced. I think you should use QDrop/AdaRound fake quantizers for PTQ.
```
Traceback (most recent call last):
  File "quant_v1.py", line 158, in <module>
    main()
  File "quant_v1.py", line 136, in main
    model = ptq_reconstruction(model, stacked_tensor, EasyDict(ptq_reconstruction_config))
  File "/tmp/MQBench/mqbench/advanced_ptq.py", line 676, in ptq_reconstruction
    subgraph_reconstruction(subgraph, cached_inps, cached_oups, config)
  File "/tmp/MQBench/mqbench/advanced_ptq.py", line 295, in subgraph_reconstruction
    weight_quantizer.init(layer.weight.data, config.round_mode)
  File "/anaconda3/envs/quant/lib/python3.8/site-packages/torch/nn/modules/module.py", line 947, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'LearnableFakeQuantize' object has no attribute 'init'
```

**Comment by PannenetsF** [comment]
Though I do not re-produce this issue, but something else is also valuable. The `interpolate` used here get a `kwargs` besides `args` which is not supported by MQBench now.

**Comment by PannenetsF** [comment]
I will open a new issue to track the kwargs problem.

**Comment by feixiang7701** [comment]
Thank you for your meticulous and excellent work!
