### ISSUE TITLE
关于TQT的疑问

### ISSUE THREAD

**Issue by PuNeal** [ModelTC/MQBench#118]
在看到TQT部分的源码时，发现scale被设置为不可训练的参数，看了下commit信息，发现之前是设置为可训练的，请问为什么要做这种改动呢？有什么好处吗？
这个是发生更改时候的pull链接：https://github.com/ModelTC/MQBench/pull/54/files

**Comment by PannenetsF** [comment]
经验表明固定住scale的时候，效果会好一点，因为离散到只能是二的幂次方，训练效果不太好。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年6月17日(周五) 下午5:55
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [ModelTC/MQBench] 关于TQT的疑问 (Issue #118)




 
在看到TQT部分的源码时，发现scale被设置为不可训练的参数，看了下commit信息，发现之前是设置为可训练的，请问为什么要做这种改动呢？有什么好处吗？
 这个是发生更改时候的pull链接：https://github.com/ModelTC/MQBench/pull/54/files

**Comment by crleagure** [comment]
> 经验表明固定住scale的时候，效果会好一点，因为离散到只能是二的幂次方，训练效果不太好。
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2022年6月17日(周五) 下午5:55 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [ModelTC/MQBench] 关于TQT的疑问 (Issue #118) 在看到TQT部分的源码时，发现scale被设置为不可训练的参数，看了下commit信息，发现之前是设置为可训练的，请问为什么要做这种改动呢？有什么好处吗？ 这个是发生更改时候的pull链接：https://github.com/ModelTC/MQBench/pull/54/files — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

TQT算法论文里面求阈值的时候是往上取整，计算大于t的最小PoT，但是mqbench是向下取整，计算的是小于t的最大PoT，这是不是不太对
