### ISSUE TITLE
About MQBench future

### ISSUE THREAD

**Issue by www516717402** [ModelTC/MQBench#12]
Thank you for open this great project.
1. when will update next version? and what content in it?
2. Hope write readme for more details.
3. Where is Examle? How to use it better?

**Comment by Tracin** [comment]
We are scheduling a regular releasing plan recently to make this project more active. For next version, deployment on TVM and experiment settings in MQBench papaer are important.
You can try imagenet training and TensorRT deployment after reading this https://github.com/ModelTC/MQBench/tree/master/application/imagenet_example

**Comment by www516717402** [comment]
@Tracin Thanks reply rapidly.  I  am doing quantize detection model by this project in current. This project is great.
I guess pytorch will update quantize module in version 1.10 since it move all quantize function to [torch.ao](https://github.com/pytorch/pytorch/tree/master/torch/ao/quantization).

**Comment by XHPlus** [comment]
@www516717402 Yes, we also noticed the update of PyTorch. We will keep pace with PyTorch and make our project compatible with the latest version.

**Comment by www516717402** [comment]
Look forward update comming.
