### ISSUE TITLE
PTQ和QAT生成的文件如何转换成.engine文件

### ISSUE THREAD

**Issue by Shining-Tears** [ModelTC/MQBench#120]
现在可以通过PTQ/QAT生三个文件，包括两个onnx和一个json，那么该如何变成tensorrt的文件格式呢？
<img width="172" alt="image" src="https://user-images.githubusercontent.com/91664480/175185272-31254828-7b3c-439d-b3b2-4458b063d7aa.png">

**Comment by tuochi** [comment]
例子代码库有[链接](https://github.com/ModelTC/MQBench/blob/main/application/imagenet_example/onnx2trt.py)

**Comment by Shining-Tears** [comment]
谢谢~ 例子中的onnx生成的engine是fp32的吧
，在后面加上--clip-range-file <jison文件位置>能生成int8的engine吗？

**Comment by Shining-Tears** [comment]
然后试了一下，两个engine文件大小并没有差距很大，正常情况int8的engine不是应该比fp32的engine小很多吗？

**Comment by Shining-Tears** [comment]
@tuochi 麻烦了~
