### ISSUE TITLE
advanced pto 方式报错

### ISSUE THREAD

**Issue by GtxMiracle** [ModelTC/MQBench#122]
根据文档，使用advanced ptq对torch官方mobilenet v2模型进行定点化，但是在测试过程中遇到了如下问题：
1. 文档中给出的ptq_reconstruction_config会报错
文档中的ptq_reconstruction_config为字典类型，但是实际代码在消费这个config时既用到了字典访问，又用到了attribute访问，导致报错：
在advanced_ptq534行：
    if not config.keep_gpu:
        cali_data = [to_device(inp, 'cpu') for inp in cali_data]
    '''set state first'''
在advanced_ptq581行：
    for node in nodes:
        if 'exclude_node_prefix' in config:
            cont = False
            for prefix in config['exclude_node']:
                if node.name.startswith(prefix):
                    cont = True
                    break
该问题通过如下定义方式可以绕过：
class DictToClass(dict):
    def __init__(self, _obj):
        super(DictToClass, self).__init__()
        if _obj:
            self.__dict__.update(_obj)
ptq_reconstruction_config = {
    'pattern': 'block',                   #? 'layer' for Adaround or 'block' for BRECQ and QDROP
    'scale_lr': 4.0e-5,                   #? learning rate for learning step size of activation
    'warm_up': 0.2,                       #? 0.2 * max_count iters without regularization to floor or ceil
    'weight': 0.01,                       #? loss weight for regularization item
    'max_count': 20000,                   #? optimization iteration
    'b_range': [20,2],                    #? beta decaying range
    'keep_gpu': True,                     #? calibration data restore in gpu or cpu
    'round_mode': 'learned_hard_sigmoid', #? ways to reconstruct the weight, currently only support learned_hard_sigmoid
    'prob': 1.0,                          #? dropping probability of QDROP, 1.0 for Adaround and BRECQ
}

2. 定点化过程中，遇到如下报错信息：
Traceback (most recent call last):
  File "/home/juanji/workspace/codes/pto_mqbench/pto_advanced.py", line 43, in <module>
    model = ptq_reconstruction(model, stacked_tensor, ptq_reconstruction_config)
  File "/home/juanji/.conda/envs/mqbench/lib/python3.6/site-packages/MQBench-0.0.6-py3.6.egg/mqbench/advanced_ptq.py", line 668, in ptq_reconstruction
    subgraph_reconstruction(subgraph, cached_inps, cached_oups, config)
  File "/home/juanji/.conda/envs/mqbench/lib/python3.6/site-packages/MQBench-0.0.6-py3.6.egg/mqbench/advanced_ptq.py", line 295, in subgraph_reconstruction
    weight_quantizer.init(layer.weight.data, config.round_mode)
  File "/home/juanji/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 948, in __getattr__
    type(self).__name__, name))
AttributeError: 'TqtFakeQuantize' object has no attribute 'init'
使用TensorRT、ONNXQNN和Vitis均遇到类似报错。
请问应该如何才能够正确运行advanced ptq方式？

**Comment by PannenetsF** [comment]
请分别使用qdrop/adaround fake quantizer作为ptq的acti/weight的fq



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年7月1日(周五) 中午11:34
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [ModelTC/MQBench] advanced pto 方式报错 (Issue #122)




 
根据文档，使用advanced ptq对torch官方mobilenet v2模型进行定点化，但是在测试过程中遇到了如下问题：
  
 
文档中给出的ptq_reconstruction_config会报错
 文档中的ptq_reconstruction_config为字典类型，但是实际代码在消费这个config时既用到了字典访问，又用到了attribute访问，导致报错：
 在advanced_ptq534行：
 if not config.keep_gpu:
 cali_data = [to_device(inp, 'cpu') for inp in cali_data]
 '''set state first'''
 在advanced_ptq581行：
 for node in nodes:
 if 'exclude_node_prefix' in config:
 cont = False
 for prefix in config['exclude_node']:
 if node.name.startswith(prefix):
 cont = True
 break
 该问题通过如下定义方式可以绕过：
 class DictToClass(dict):
 def init(self, _obj):
 super(DictToClass, self).init()
 if _obj:
 self.dict.update(_obj)
 ptq_reconstruction_config = {
 'pattern': 'block',                   #? 'layer' for Adaround or 'block' for BRECQ and QDROP
 'scale_lr': 4.0e-5,                   #? learning rate for learning step size of activation
 'warm_up': 0.2,                       #? 0.2 * max_count iters without regularization to floor or ceil
 'weight': 0.01,                       #? loss weight for regularization item
 'max_count': 20000,                   #? optimization iteration
 'b_range': [20,2],                    #? beta decaying range
 'keep_gpu': True,                     #? calibration data restore in gpu or cpu
 'round_mode': 'learned_hard_sigmoid', #? ways to reconstruct the weight, currently only support learned_hard_sigmoid
 'prob': 1.0,                          #? dropping probability of QDROP, 1.0 for Adaround and BRECQ
 }
 

 
定点化过程中，遇到如下报错信息：
 Traceback (most recent call last):
 File "/home/juanji/workspace/codes/pto_mqbench/pto_advanced.py", line 43, in 
 model = ptq_reconstruction(model, stacked_tensor, ptq_reconstruction_config)
 File "/home/juanji/.conda/envs/mqbench/lib/python3.6/site-packages/MQBench-0.0.6-py3.6.egg/mqbench/advanced_ptq.py", line 668, in ptq_reconstruction
 subgraph_reconstruction(subgraph, cached_inps, cached_oups, config)
 File "/home/juanji/.conda/envs/mqbench/lib/python3.6/site-packages/MQBench-0.0.6-py3.6.egg/mqbench/advanced_ptq.py", line 295, in subgraph_reconstruction
 weight_quantizer.init(layer.weight.data, config.round_mode)
 File "/home/juanji/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 948, in getattr
 type(self).name, name))
 AttributeError: 'TqtFakeQuantize' object has no attribute 'init'
 使用TensorRT、ONNXQNN和Vitis均遇到类似报错。
 请问应该如何才能够正确运行advanced ptq方式？
