### ISSUE TITLE
Inconsistent versions of opset when deploy_to_qlinear =True

### ISSUE THREAD

**Issue by pycoco** [ModelTC/MQBench#123]
Now  we register  LearnablePerTensorAffine, FixedPerChannelAffine, FixedPerTensorAffine under opset 11. 
https://github.com/ModelTC/MQBench/blob/main/mqbench/custom_symbolic_opset.py#L9
But when we set deploy_to_qlinear =True, the opset is set to 13.
https://github.com/ModelTC/MQBench/blob/main/mqbench/convert_deploy.py#L68.
At this time, we don't register LearnablePerTensorAffine, FixedPerChannelAffine, FixedPerTensorAffine op.

**Comment by Tracin** [comment]
I understand the mismatch between opset versions.
Could you explain more detail, like what kind of error will occur under which process.
Thanks!
