### ISSUE TITLE
Bad performance for UNet3D with TensorRT backend

### ISSUE THREAD

**Issue by urbste** [ModelTC/MQBench#129]
I created 3 scripts to quantize a UNet3D for inference on a NVidia Xavier, i.e. for the TensorRT backend.
I attached the 3 scripts I used in the zip file. 

First script "1_quantize_unet3d.py" creates onnx and clip ranges.
The conversion runs without any problems.
However I noticed, that there is only a single blob range value, although the simple UNet3D with depth=1 has 2 DoubleConv3D layer as well as a Conv layer as output?!

The second script "2_create_trt_engine_from_mqbench_onnx.py" creates and saves the trt engine file.
With the third script 3_run_inference.py the inference times are reported.

On a Nvidia Xavier I get this output with MQBench:
```
Starting inference
[07/05/2022-13:54:30] [TRT] [I] [MemUsageChange] Init CUDA: CPU +202, GPU +0, now: CPU 280, GPU 6232 (MiB)
[07/05/2022-13:54:31] [TRT] [I] Loaded engine size: 0 MiB
[07/05/2022-13:54:32] [TRT] [I] [MemUsageChange] Init cuDNN: CPU +344, GPU +324, now: CPU 645, GPU 6576 (MiB)
[07/05/2022-13:54:32] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in engine deserialization: CPU +0, GPU +0, now: CPU 0, GPU 0 (MiB)
[07/05/2022-13:54:32] [TRT] [I] [MemUsageChange] Init cuDNN: CPU +0, GPU +0, now: CPU 644, GPU 6576 (MiB)
[07/05/2022-13:54:32] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in IExecutionContext creation: CPU +0, GPU +732, now: CPU 0, GPU 732 (MiB)
**Time per sample: 0.450s
Total time for 20 volumes: 8.999s**
```
So I am getting 0.45s per volume.

** Now the issue:  **
I did the same thing with onnxruntime and different execution providers.
I also ran a simple calibration routine to get the calibration.flatbuffers and they have a lot more quanization ranges than the clip_ranges.json file from MQBench

Runtimes with onnxruntime and CUDA and TRT providers: 
```
Total elapsed time: 8.083297729492188
Time per volume crop Pytorch CUDA FP32: 0.40416

Total elapsed time: 2.546628952026367
Time per volume crop Pytorch CUDA FP16: 0.12733

Total elapsed time: 11.080541372299194
Time per volume crop ONNX CUDA Provider FP32: 0.55403

Total elapsed time: 2.496774673461914
Time per volume crop ONNX TRT Provider FP16: 0.12484

Total elapsed time: 2.0073330402374268
Time per volume crop ONNX TRT Provider INT8: 0.10037
```

So I am getting 4 times faster inference with using onnxruntime quantization then using MQBench. What am I doing wrong?

Example for INT8 providers setting with onnxruntime:
```
providers = [
    ('TensorrtExecutionProvider', {
        'device_id': 0,
        'trt_max_workspace_size': 2147483648,
        'trt_int8_enable': True,
        'trt_int8_calibration_table_name': "calibration.flatbuffers",
        'trt_engine_cache_enable': True,
        'trt_engine_cache_path': "onnx_int8_trt_cache"
    })
]
```

**Comment by urbste** [comment]
Here is a minimal sample of the MQBench UNet3D export and conversion to TensorRT.
[MinimalExampleUnet3DTRT.zip](https://github.com/ModelTC/MQBench/files/9046498/MinimalExampleUnet3DTRT.zip)

**Comment by Tracin** [comment]
That is very interesting, I will check it at once.

**Comment by Tracin** [comment]
Conv3d not supported yet, so Conv3d + bn is not merged which makes it slow.
`extra_config = {                                                                                                                                                                                                                                                                                                                                              
     "extra_quantizer_dict": {                                                                                                                                                                              
         "additional_module_type": (torch.nn.Conv3d, torch.nn.MaxPool3d,),                                                                                                                                  
         "additional_function_type": [torch.cat,]                                                                                                                                                           
     }                                                                                                                                                                                                      
 }                                            
`
besides, you need to update extra_config as above.

**Comment by Tracin** [comment]
[unet.zip](https://github.com/ModelTC/MQBench/files/9157445/unet.zip)
