### ISSUE TITLE
symbolic_trace出错

### ISSUE THREAD

**Issue by NickYangMin** [ModelTC/MQBench#13]
在mmdetecion上使用你们这个代码，symbolic_trace会出错，你们有尝试过吗？

**Comment by www516717402** [comment]
@NickYangMin 我正在使用这个库量化mmdetection，可以交流一下www516717402@gmail.com

**Comment by Tracin** [comment]
fx.trace属于静态,所以模型中的动态特性无法被追踪,可以尝试修改模型定义

**Comment by Tracin** [comment]
欢迎尝试检测框架EOD,支持量化训练
https://github.com/ModelTC/EOD
