### ISSUE TITLE
QAT训练过程不收敛

### ISSUE THREAD

**Issue by YeahTech** [ModelTC/MQBench#132]
在使用MQBench进行量化感知训练时模型不收敛。
方式：
1.先正常训练完模型
2.加载训练完的模型权重，并使用QAT的方式训练，流程和https://github.com/ModelTC/MQBench/blob/main/application/imagenet_example/main.py 几乎完全一样

尝试了调小学习率，但是还是无法收敛

**Comment by PannenetsF** [comment]
最好给出相关的模型定义，量化模型后端以及用的fake quant，QAT训练配置
