### ISSUE TITLE
对yolov5进行ptq时（tensorrt平台），生成带Q、DQ节点的onnx发生错误， Graph is illegel, error occured!

### ISSUE THREAD

**Issue by Shining-Tears** [ModelTC/MQBench#133]
代码如下，如果设置deploy_to_qlinear=True会报错，deploy_to_qlinear=False不会报错：

from models.experimental import attempt_load
from mqbench.prepare_by_platform import prepare_by_platform, BackendType
from mqbench.convert_deploy import convert_deploy
from mqbench.utils.state import enable_calibration, enable_quantization, enable_calibration_woquantization
# 准备模型
import torch
import glob
import os
from PIL import Image
model = attempt_load('/home/chenwz/code/yolov5-6.0/yolov5s.pt', map_location='cuda')
model.train()
device = torch.device('cuda')
model = model.to(device)
files_path = '/home/chenwz/code/data/cali'
imgs = glob.glob(os.path.join(files_path, '*'))

datas = []
import torchvision.transforms as transforms
transform = transforms.Compose([
            transforms.Resize([640, 640]),  # [h,w]
            transforms.ToTensor(),
        ])
for i, f in enumerate(imgs):
                img = Image.open(f).convert('RGB')
                img = transform(img)
                img = img.unsqueeze(0)
                datas.append(img)

extra_prepare_dict={'extra_qconfig_dict':{
    'w_observer': 'MSEObserver',
    'a_observer': 'EMAMSEObserver',
    'w_fakequantize': 'AdaRoundFakeQuantize',
    'a_fakequantize': 'FixedFakeQuantize',
    'w_qscheme':{ 'bit': 8,'symmetry': True,'per_channel': True,'pot_scale': False,'p': 2.4},
    'a_qscheme':{'bit': 8,'symmetry': True,'per_channel': False,'pot_scale': False,'p': 2.4}}}

model = prepare_by_platform(model, BackendType.Tensorrt, extra_prepare_dict).to(device)
model.eval()

enable_calibration_woquantization(model, quantizer_type='act_fake_quant')
for i in datas:
    model(i.cuda())
enable_calibration_woquantization(model, quantizer_type='weight_fake_quant')
model(datas[0].cuda())

enable_quantization(model)
for i in datas:
    model(i.cuda())
convert_deploy(model, BackendType.Tensorrt, {'x': [1, 3, 640, 640]}, model_name='yolo_s',deploy_to_qlinear=True)

error：
    convert_deploy(model, BackendType.Tensorrt, {'x': [1, 3, 640, 640]}, model_name='yolo_s',deploy_to_qlinear=True)
  File "/home/chenwz/.conda/envs/nni-wenze/lib/python3.8/site-packages/MQBench-0.0.6-py3.8.egg/mqbench/convert_deploy.py", line 184, in convert_deploy
    convert_function(deploy_model, **kwargs)
  File "/home/chenwz/.conda/envs/nni-wenze/lib/python3.8/site-packages/MQBench-0.0.6-py3.8.egg/mqbench/convert_deploy.py", line 96, in convert_onnx_qlinear
    ONNXQLinearPass(onnx_model_path).run()
  File "/home/chenwz/.conda/envs/nni-wenze/lib/python3.8/site-packages/MQBench-0.0.6-py3.8.egg/mqbench/deploy/deploy_onnx_qlinear.py", line 137, in run
    self.onnx_model.optimize_model()
  File "/home/chenwz/.conda/envs/nni-wenze/lib/python3.8/site-packages/MQBench-0.0.6-py3.8.egg/mqbench/deploy/common.py", line 139, in optimize_model
    assert node_detect, "Graph is illegel, error occured!"
AssertionError: Graph is illegel, error occured!

**Comment by Tracin** [comment]
Tensorrt部署导出会有两种途径, 看起来其中一种存在bug
可以分享一下具体的模型定义吗?(`attempt_load`)
方便定位问题
