### ISSUE TITLE
how to ptq for Faster RCNN or SSD？

### ISSUE THREAD

**Issue by wangshankun** [ModelTC/MQBench#134]
From QDROP paper，i notice the benchmark result include Faster RCNN；
![image](https://user-images.githubusercontent.com/3970271/177967270-99e64612-3384-46bb-b4db-d2fbb1356067.png)

Could you  provide  this examples？

In addition, it's best to provide  PTQ of SSD，another import object detection network；

**Comment by PannenetsF** [comment]
https://github.com/ModelTC/United-Perception/tree/main/configs/quant/det <https://github.com/ModelTC/United-Perception/tree/main/configs/quant/det>

Here are configs for the FRCNN and RetinaNet, with which you can easily re-produce qdrop/brecq/adaround on detection task via the united-perception framework. 

We did not do PTQ on SSD, you can try it out just like the other cls networks.

**Comment by wangshankun** [comment]
@PannenetsF 感谢及时答复；
我的理解检测模型的ptq不需要train会比给出的sample config要简单不少，但是检测模型的ptq没办法直接比对cls网络；因为网络的neck部分是需要做处理的；

我看工具链team在B站视频里面介绍要配合EOD的代码，注册submodule···看起来还是很麻烦的

**Comment by PannenetsF** [comment]
理解部分可以说的详细一点，有点不明白；

注册的话还是比较简单，和正常搭建网络工作量差别不大。

**Comment by wangshankun** [comment]
> 
我看分析了你给我的链接，
https://github.com/ModelTC/United-Perception/blob/main/configs/quant/det/yolox/yolox_fpga_quant_vitis_qat.yaml
这是检测网络的qat，有点复杂，以至于我没有能力从这个config里面摘录出yolox的ptq

**Comment by PannenetsF** [comment]
可以参考同目录下的ptq config

**Comment by wangshankun** [comment]
> 可以参考同目录下的ptq config

有det系列的 ptq config参考吗？

**Comment by wangshankun** [comment]
> 可以参考同目录下的ptq config

@PannenetsF 有det系列模型的 ptq config参考吗？

**Comment by PannenetsF** [comment]
https://github.com/ModelTC/United-Perception/tree/main/configs/quant/det

**Comment by wangshankun** [comment]
> https://github.com/ModelTC/United-Perception/tree/main/configs/quant/det

多谢！找到了一个合适的参考
https://github.com/ModelTC/United-Perception/blob/main/configs/quant/det/retinanet/retinanet-r50-w2a4-ada.yaml

**Comment by wangshankun** [comment]
> https://github.com/ModelTC/United-Perception/tree/main/configs/quant/det

EOD自己给的例子，config中的quant_ptq是不支持的
![image](https://user-images.githubusercontent.com/3970271/178963145-343247c1-3124-4f1a-8c68-4d4fe3027153.png)

问题提交
https://github.com/ModelTC/United-Perception/issues/29
