### ISSUE TITLE
[BUG]  Zero-point must be Long, found Int；  _version_under_1100  判断方式对torch 1.10版本无效

### ISSUE THREAD

**Issue by wangshankun** [ModelTC/MQBench#141]
_version_under_1100  

![image](https://user-images.githubusercontent.com/3970271/178710603-b5049332-efb2-4d28-9f99-17422abb2f99.png)

![image](https://user-images.githubusercontent.com/3970271/178709426-8749e9c7-8468-4bb6-bc05-c1cb1d80c6aa.png)

1.10的torch版本也是需要用long的
![image](https://user-images.githubusercontent.com/3970271/178709672-157bfa03-68fa-430a-b3d8-8a8540e9d515.png)

**Comment by Tracin** [comment]
1.10.0测过是没问题的, 这个1.10.0a0是什么版本

**Comment by wangshankun** [comment]
> 1.10.0测过是没问题的, 这个1.10.0a0是什么版本

NVIDIA官方提供的torch container
nvcr.io/nvidia/pytorch      21.07-py3

**Comment by wangshankun** [comment]
https://docs.nvidia.com/deeplearning/frameworks/support-matrix/index.html
 
![image](https://user-images.githubusercontent.com/3970271/180356507-f6cb33f1-df60-4ec6-910b-55949fdcb386.png)
