### ISSUE TITLE
academic 不执行算子融合吗？为什么还多插入了BN节点；

### ISSUE THREAD

**Issue by wangshankun** [ModelTC/MQBench#142]
resent50原始模型没有BN，导出的量化模型不仅多了BN，BN+relu也没融合

![image](https://user-images.githubusercontent.com/3970271/178889732-2325365b-6f39-4da7-83ca-474083516dcd.png)

openvino应该把BN融合到Conv，但是Rule还在，没有conv+bn+relu融合规则吗？

![image](https://user-images.githubusercontent.com/3970271/178889643-0c7edbd7-c157-47da-8aa9-785f71127697.png)

![image](https://user-images.githubusercontent.com/3970271/178889533-6dbf1007-a2ce-431f-8a90-d4d00f606414.png)

**Comment by PannenetsF** [comment]
fuse bn是为了提高推理效率的，academic 模型不执行fuse bn，其他后端执行。
