### ISSUE TITLE
Convert the quantized model to ONNX failed.

### ISSUE THREAD

**Issue by lqwang1025** [ModelTC/MQBench#147]
Hi, Thank you for providing me with such a powerful quantize tool. There is a question：

Isn't it possible to combine various quantization algorithms with the backend at will? If yes, when i used
<img width="645" alt="1658621357232" src="https://user-images.githubusercontent.com/35258580/180626827-1ffd0ea1-2558-423e-9816-7da5baebbd50.png">
the config like this, convert the model to ONNX will crash.  I located that the problem was caused by the maximum and minimum values being placed in the node attribute.
<img width="390" alt="1658621477591" src="https://user-images.githubusercontent.com/35258580/180626863-fae0c0f3-e898-4140-bde6-896fd5b88b8b.png">

**Comment by PannenetsF** [comment]
You can provide a minimal code snippets containing network defination, quantization config and convert config.
