### ISSUE TITLE
YOLOX 在onnxruntime上运行出错！

### ISSUE THREAD

**Issue by lqwang1025** [ModelTC/MQBench#148]
原因是，resize节点不量化，当**resize**-->a的son节点是**concat**，并且concat的另一个parent节点是**QuantizeLinear**-->b的时候就会由于输入的datatype不同而出现问题，建议在convert to onnx 的时候遇到这种情况将concat的b输入分支连接r如下图的到Mul节点。
<img width="513" alt="1658622116811" src="https://user-images.githubusercontent.com/35258580/180627138-9b99b7b6-8b5f-4ace-9b1a-f13356977fd7.png">

**Comment by Tracin** [comment]
非常感谢，ONNX后端并没有做非常充足的测试，还需要不断完善
可否提供网络定义，以尽快修复问题
