### ISSUE TITLE
recommend that move PerChannelLoadHook definition to the global space to support python pickle

### ISSUE THREAD

**Issue by un-knight** [ModelTC/MQBench#154]
Currently, the class `PerChannelLoadHook ` is defined as a local class under the scope of `ObserverBase`, but this type of code structure can raise a pickle error `can't pickle local object .....` if someone tries to pickle an observer object.

So I suggest that move `PerChannelLoadHook ` definition into the global scope if there are no special reasons.

## relation codes
https://github.com/ModelTC/MQBench/blob/759c445c638ee3add1df7045af686ed313d06b5d/mqbench/observer.py#L28-L66

**Comment by PannenetsF** [comment]
Could you provide a minimal code to re-produce this issue? I have used this hook for a long time without errors.

**Comment by un-knight** [comment]
@PannenetsF For example:
```python
import torch.fx
import torch.nn as nn
from mqbench.prepare_by_platform import prepare_by_platform, BackendType
from mqbench.convert_deploy import convert_deploy

class ToyModule(nn.Module):

    def __init__(self) -> None:
        super().__init__()
        self.conv = nn.Conv2d(10, 2, 3)

    def forward(self, x):
        return self.conv(x)


model = ToyModule()
model.train()
model: torch.fx.GraphModule = prepare_by_platform(model, BackendType.SNPE)
print(model)
model.to_folder("toy_model", "conv2d")
```

We will get the following errors by running this script:

```
Traceback (most recent call last):
  File "case.py", line 20, in <module>
    model.to_folder("toy_model", "conv2d")
  File "/home/xxx/anaconda3/envs/mqbench-test/lib/python3.8/site-packages/torch/fx/graph_module.py", line 384, in to_folder
    torch.save(module, module_file)
  File "/home/xxx/anaconda3/envs/mqbench-test/lib/python3.8/site-packages/torch/serialization.py", line 379, in save
    _save(obj, opened_zipfile, pickle_module, pickle_protocol)
  File "/home/xxx/anaconda3/envs/mqbench-test/lib/python3.8/site-packages/torch/serialization.py", line 484, in _save
    pickler.dump(obj)
AttributeError: Can't pickle local object 'ObserverBase.__init__.<locals>.PerChannelLoadHook'
```

**Comment by PannenetsF** [comment]
I've checked this. The perchannel_hook has been moved to `mqbench.utils.hook` already, this missed local defination will be fix ASAP.

**Comment by PannenetsF** [comment]
https://github.com/ModelTC/MQBench/pull/159
