### ISSUE TITLE
希望tensorrt-nlp后端加上torch.nn.Conv2d

### ISSUE THREAD

**Issue by HawkL327** [ModelTC/MQBench#160]
打印看了下module_type_to_quant_input只有(<class 'torch.nn.qat.modules.linear.Linear'>, <class 'mqbench.nn.intrinsic.modules.fused.ConvFreezebn2d'>, <class 'mqbench.nn.intrinsic.modules.fused.ConvFreezebnReLU2d'>)
在swintransformer里面，现在跑tensorrtnlp后端，首层有个conv没有被量化

**Comment by Tracin** [comment]
可以加到
`
{
"extra_quantizer_dict": {
"additional_module_type": torch.nn.Conv2d
}
}
`
