### ISSUE TITLE
关于 pot_quantization 和 sync_tensor 执行顺序的疑问

### ISSUE THREAD

**Issue by humu789** [ModelTC/MQBench#161]
在observer里，pot_quantization 是不是应该在 sync_tensor 做更合适，这样才能保证最后的 scale 是 pot，先做了 pot_quantization 再做sync_tensor，scale 被平均了以后不能保证是 pot 类型

**Comment by PannenetsF** [comment]
https://github.com/ModelTC/MQBench/blob/main/mqbench/observer.py#L50-L54

**Comment by PannenetsF** [comment]
修了有一段时间了
