### ISSUE TITLE
请问这里为啥会爆出警告

### ISSUE THREAD

**Issue by LHH20000923** [ModelTC/MQBench#163]
TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
![1](https://user-images.githubusercontent.com/83012544/182591082-3e76785d-2b03-4066-907c-793f7cd9617e.png)

**Comment by LHH20000923** [comment]
然后这个警告又是什么导致的呢？
![1](https://user-images.githubusercontent.com/83012544/182591405-858a01d8-0977-44cd-8b82-d1d88d652585.png)

**Comment by PannenetsF** [comment]
observer里有fake quant还有observe的开关，只要trace阶段不改变这些参数就可以忽略；onnx导出过程中fake quant并不会真的导出到硬件，shape infer没处理。
