### ISSUE TITLE
使用MQBench commit:a5582f416d62d9c40d3f5023b81ce71bb8791dd9 导出resnet到tengine，fp32到uint8，精度下降30个点

### ISSUE THREAD

**Issue by RedHandLM** [ModelTC/MQBench#166]
!!!!!!!!!!首先声明!!!!!!!!!!
这个问题是基于commit:a5582f416d62d9c40d3f5023b81ce71bb8791dd9 进行的，因为当前的master版本导出tengine的时候scale文件是空的，所以基于这个版本进行转换。

使用这个版本的mqbench对resnet进行qat训练，qat训练精度基本保持不变，acc在90左右，然后使用convert_deploy对qat训练的模型进行导出，指定BackendType=Tengine_u8，导出结果是onnx和对应的scale，onnx在nerton中可以正常打开，scale查看也无异常，然后使用tengine的转换工具，先把onnx转换为tmfile,  再使用tengine的后量化工具 quant_tools_uint8  加载已转换的tmfile和scale 进行量化，出来的uint8模型，可以使用tengine在npu上面推理，但是精度降低到0.58，使用量化工具看到的cosin余弦 最后几层在0.5 0.6左右，正常应该在0.8-0.9左右

所以目前这个问题出在哪里？是生成的scale有问题呢？还是因为tengine和mqbench的一些节点没有对齐，希望协助看下这个问题，非常感谢

以下是qat之后mqbench导出的scale，模型较大无法上传

链接: https://pan.baidu.com/s/1FbdT7ZHEYnciIQKcWtlMVg 提取码: cz7f

**Comment by Tracin** [comment]
@un-knight Any suggestions?

**Comment by RedHandLM** [comment]
基于最新的master分支
基于最新的master分支
基于最新的master分支，也重新做了实验，输入形状改成 [3,224,224] 精度稍有提升，从0.58提升到0.64
env如下:
ubuntu20.04
torch==1.8.1
torchvision==0.9.1
MQBench==0.0.6
cuda==11.2

我们在训练框架中集成了mqbench， 以下为示例代码, 基本流程与下面步骤一致，模型是原生resnet，除了最后的分类层其他层没有进行改造
```
model_to_quantize = models.resnet18(pretrained=False)
dummy_input = torch.randn(1, 3, 224, 224, device='cpu')
model_to_quantize.train()
model_prepared = prepare_by_platform(model_to_quantize, BackendType.Tengine_u8)
enable_calibration(model_prepared)
model_prepared(dummy_input)
enable_quantization(model_prepared)
loss = model_prepared(dummy_input).sum()
loss.backward()
model_prepared.eval()
convert_deploy(model_prepared, BackendType.Tengine_u8, {'x': [1, 3, 224, 224]}, model_name='resnet18')
```

**Comment by RedHandLM** [comment]
链接内为qat onnx和tengine导出后的onnx
链接: https://pan.baidu.com/s/1PqBVXJTYphpzPQ8m1cWHCQ 提取码: d65p

**Comment by un-knight** [comment]
@RedHandLM 初步来看，这个计算图的量化节点插入有点奇怪，比如下图中，这两个conv之间红框内的fake quantize节点是多余的，有可能这里的冗余信息导致tengine convert tool解析时候使用了不合适的量化参数：
![image](https://user-images.githubusercontent.com/8266614/184307004-87505209-ef3e-4b98-8a15-3fdb30254c30.png)

**Comment by un-knight** [comment]
@RedHandLM 这是我基于mqbench最新master导出的计算图，显然你的计算图中伪量化节点插入逻辑和预期的并不一致，你是不是对本地的tengine quantizer做过什么修改？

我执行的参考[main.py](https://github.com/ModelTC/MQBench/blob/main/application/imagenet_example/main.py)，执行指令`python main.py --train_data ~/datasets/imagenet_1k/ --val_data ~/datasets/imagenet_1k/ -a resnet18 --pretrained --gpu 0 --backend tengine_u8 --deploy`

![mqbench_qmodel onnx](https://user-images.githubusercontent.com/8266614/184334147-39183928-a144-4426-a522-217f16f01d52.png)

**Comment by shijie-nv** [comment]
@un-knight  @un-knight 
我遇到类似的问题，结果更加的差，完全参照User Guide进行的

和 @un-knight 上条帖子一样的命令
python main.py \
--train_data ~/datasets/imagenet_1k/ \
--val_data ~/datasets/imagenet_1k/ \
-a resnet18 \
--pretrained \
--gpu 0 \
--backend tengine_u8 \
--deploy

然后转换
convert_tool -f onnx -m mqbench_qmodel_for_tengine.onnx -o resnet18_fp32.tmfile
量化
quant_tool_uint8 -m resnet18_fp32.tmfile -o resnet18_u8.tmfile -i ./ -f mqbench_qmodel_for_tengine.scale

用例子里提供的 eval_tengine.py 测试
python eval_tengine.py --dataset /home/csj/cache/imagenet2012_tiny -m resnet18_fp32.tmfile
Final ==> * Acc@1 70.000 Acc@5 88.550

python eval_tengine.py --dataset /home/csj/cache/imagenet2012_tiny -m resnet18_u8.tmfile
Final ==> * Acc@1 0.150 Acc@5 0.600

浮点结果正常，量化模型只有 0.15精度！！！
由于imagenet2012的val集有50000张图片，eval_tengine.py运行的太慢，我这里imagenet2012_tiny就是每类取2张图片，2000张图片跑eval_tengine.py，结果和跑50000张测试是差不多的。

上面的--deploy命令，虽然仅仅用到10次calibration，由于resnet18对于量化是非常友好的，应该没问题啊。
要么我还是训练一下吧

训练设置
python main.py \
--train_data ~/datasets/imagenet_1k \
--val_data ~/datasets/imagenet_1k \
--epochs 10 --batch-size 128 \
--learning-rate 1e-4 \
--weight-decay 1e-4 \
--optim sgd \
--backend tengine_u8 \
--pretrained \
--arch resnet18 \
--gpu 0

跑了一天多，5个epocs，看上去够了
 * Acc@1 69.936 Acc@5 89.270
 * Acc@1 69.970 Acc@5 89.262
 * Acc@1 69.954 Acc@5 89.256
 * Acc@1 70.024 Acc@5 89.376
 * Acc@1 70.090 Acc@5 89.332

--deploy命令
python main.py \
--train_data ~/datasets/imagenet_1k \
--val_data ~/datasets/imagenet_1k \
--deploy \
--backend tengine_u8 \
--arch resnet18 \
--resume model_best.pth.tar \
--gpu 0

然后转换转换再测
resnet18_fp32.tmfile
 Final ==> * Acc@1 70.150 Acc@5 88.900
resnet18_u8.tmfile
 Final ==> * Acc@1 0.100 Acc@5 0.550
这次只有 0.1

tengine也提供的PTQ的量化方式，我用ncnn提供的1000张图
https://github.com/nihui/imagenet-sample-images
跑一遍，就用最基本的 minmax 方法，转换出一个uint8模型，
再用eval_tengine.py跑一遍
resnet18_u8.tmfile
Final ==> * Acc@1 69.050 Acc@5 88.100
完全正常，这说明eval_tengine.py 没有问题

这个测试我做了两次
第一次是 2022-07-22 的版本，这个版本升级到支持 torch 1.10.0
第二次是看到这个帖子，又看到 2022-08-02 版本修复了 Tengine_u8 backend，升级到最新
以为问题解决了，再测还是一样不行。

希望能帮忙解决一下

**Comment by un-knight** [comment]
@shijie001 感谢反馈，已经找到问题，正在修复

**Comment by un-knight** [comment]
@shijie001 试下这个PR https://github.com/ModelTC/MQBench/pull/172

**Comment by un-knight** [comment]
@RedHandLM 试下最新的master，如果问题得到解决，请关闭当前issue.

**Comment by RedHandLM** [comment]
> 

好的 我试下
