### ISSUE TITLE
Activation FakeQuantizer Insertion after Concat

### ISSUE THREAD

**Issue by a1trl9** [ModelTC/MQBench#17]
Hi, 

It seems in the current implementation of quantizer, activation `FakeQuantizer` would be inserted after concat op, like the following:

![Screen Shot 2021-10-30 at 6 09 14 PM](https://user-images.githubusercontent.com/11512033/140451300-57896986-f310-49a7-9e8b-d0d577666e44.png)

It is quite reasonable in most cases. However, if only one branch is required for inference (for example, other branchs might be only used as learning guidance), is it still the optimal choice? If it worths a try, is there any public API to support customized insertion?

Any advice would be appreciated.
﻿

**Comment by Tracin** [comment]
If any branches do not participate in learining procedure should be seperated as another model.

**Comment by a1trl9** [comment]
Thank you for your comment.

All branchs (saying B1 -- B4) used in learning but only one (saying B1) left for inference. Do you mean separate B1 and B2-B4 into two modules?

**Comment by Tracin** [comment]
Yes, try split the model. Should solve your problem.

```python
class Model(nn.Module):
    def __init__():
        self.B1 = model.b1
        self.B2 = model.b2
        ....
        prepare_by_platform(self.B1)
    
    def forward():
        b1 = self.B1(x)
        b2 = self.B2(x)
        ...
        res = torch.concat(b1, b2...)
        return res
```

**Comment by a1trl9** [comment]
Thanks!
