### ISSUE TITLE
混合精度量化相关

### ISSUE THREAD

**Issue by 666DZY666** [ModelTC/MQBench#170]
https://github.com/ModelTC/MQBench/blob/main/mqbench/mix_precision/mix_precision.py#L249
这里默认使用'naive'的方法，是实验后发现它比hawq的效果好吗~？

**Comment by 666DZY666** [comment]
https://github.com/ModelTC/MQBench/blob/c69cd0ff06ae3c981f8e7d5e0307ee98d959deff/mqbench/mix_precision/mix_precision.py#L147
这里的sensetive应该是loss - fp_loss？

**Comment by 666DZY666** [comment]
https://github.com/ModelTC/MQBench/blob/c69cd0ff06ae3c981f8e7d5e0307ee98d959deff/mqbench/mix_precision/mix_precision.py#L173
这里默认采用ILP，是因为它比preato_frontier效果好吗~？

**Comment by 666DZY666** [comment]
https://github.com/ModelTC/MQBench/blob/main/mqbench/mix_precision/hessian_per_layer.py#L76
这里分母上的trace是不是要加abs()?
参考这里：
https://github.com/amirgholami/PyHessian/blob/master/pyhessian/hessian.py#L186

**Comment by 666DZY666** [comment]
https://github.com/ModelTC/MQBench/blob/c69cd0ff06ae3c981f8e7d5e0307ee98d959deff/mqbench/mix_precision/mix_precision.py#L160
这里为啥没用
https://github.com/ModelTC/MQBench/blob/main/mqbench/mix_precision/hessian_per_layer.py#L106
这里的hessian_per_layer_acti()呢？
只获取了weight的hessian，activation的不需要吗？

**Comment by 666DZY666** [comment]
请问能否解答一下~？

**Comment by PannenetsF** [comment]
ILP和ea本质上都是求解方式，收敛性应该是差不多的；
PyHessian的trace使用eigen算得，eigen默认取正数，所以应该满足不小于0，当然加上abs更加稳妥；
acti hessian目前还是实验性质的，可以体验一番～

**Comment by yokings** [comment]
> acti hessian目前还是实验性质的，可以体验一番～

这个act hessian不需要计算类似的delta_a来计算敏感度吗？另外这个实验性质的，请问是否已经有了一些实验结果，计算的结果是否是有意义的？

**Comment by 666DZY666** [comment]
请问第1和第2个问题能否解答一下？

**Comment by 666DZY666** [comment]
https://github.com/ModelTC/MQBench/blob/main/mqbench/mix_precision/mix_precision.py#L37
这里把每层的 trace/参数量 的原因是？

**Comment by 666DZY666** [comment]
https://github.com/ModelTC/MQBench/blob/80345e58a34d13de2f7e4e9b389187abf6938f1a/mqbench/mix_precision/mix_precision.py#L211
这里pulp直接用默认的solver的ok吗？效果上有啥区别吗？
