### ISSUE TITLE
densnet121 qat导出trt后精度很低，怎么排查？

### ISSUE THREAD

**Issue by HawkL327** [ModelTC/MQBench#171]

**Comment by HawkL327** [comment]
用的命令是：
python main.py -a densenet121 --epochs 1 --lr 1e-4 --batch-size 128 --pretrained --train_data datasets/ --val_data datasets/
python onnx2trt.py --onnx mqbench_qmodel_deploy_model.onnx --trt a.trt --clip mqbench_qmodel_clip_ranges.json --data datasets --evaluate
测resnet50精度都是ok的，但是densenet121精度很低(PTQ没问题)
这个是qat的结果：
[MQBENCH] INFO: Finish deploy process.
Test: [   0/1563]       Time  5.498 ( 5.498)    Loss 3.6642e-01 (3.6642e-01)    Acc@1  96.88 ( 96.88)   Acc@5  96.88 ( 96.88)
Test: [ 100/1563]       Time  0.127 ( 1.505)    Loss 1.4376e+00 (7.2619e-01)    Acc@1  56.25 ( 81.22)   Acc@5  87.50 ( 95.24)
Test: [ 200/1563]       Time  0.144 ( 0.884)    Loss 3.8597e-01 (7.0308e-01)    Acc@1  87.50 ( 82.09)   Acc@5  96.88 ( 95.34)
Test: [ 300/1563]       Time  0.133 ( 0.659)    Loss 9.2734e-01 (6.9750e-01)    Acc@1  75.00 ( 82.02)   Acc@5  93.75 ( 95.44)
Test: [ 400/1563]       Time  0.940 ( 0.534)    Loss 5.2821e-01 (7.0936e-01)    Acc@1  87.50 ( 81.34)   Acc@5  96.88 ( 95.68)
Test: [ 500/1563]       Time  0.522 ( 0.460)    Loss 2.7362e-01 (7.2046e-01)    Acc@1  90.62 ( 81.08)   Acc@5 100.00 ( 95.70)
Test: [ 600/1563]       Time  0.133 ( 0.418)    Loss 2.6081e-01 (7.1275e-01)    Acc@1  93.75 ( 81.33)   Acc@5  96.88 ( 95.74)
Test: [ 700/1563]       Time  0.361 ( 0.389)    Loss 5.9240e-01 (7.6251e-01)    Acc@1  87.50 ( 80.14)   Acc@5  96.88 ( 95.25)
Test: [ 800/1563]       Time  0.138 ( 0.369)    Loss 3.9313e-01 (8.3371e-01)    Acc@1  84.38 ( 78.68)   Acc@5  96.88 ( 94.35)
Test: [ 900/1563]       Time  0.128 ( 0.352)    Loss 1.6248e-01 (8.5887e-01)    Acc@1  93.75 ( 78.16)   Acc@5  96.88 ( 94.01)
Test: [1000/1563]       Time  0.613 ( 0.341)    Loss 4.0168e-01 (8.9975e-01)    Acc@1  81.25 ( 77.21)   Acc@5  96.88 ( 93.49)
Test: [1100/1563]       Time  0.136 ( 0.334)    Loss 3.7730e-01 (9.2771e-01)    Acc@1  90.62 ( 76.65)   Acc@5  96.88 ( 93.17)
Test: [1200/1563]       Time  0.130 ( 0.333)    Loss 7.6897e-01 (9.5608e-01)    Acc@1  78.12 ( 76.05)   Acc@5  93.75 ( 92.78)
Test: [1300/1563]       Time  0.133 ( 0.320)    Loss 6.7102e-01 (9.7876e-01)    Acc@1  84.38 ( 75.57)   Acc@5  90.62 ( 92.50)
Test: [1400/1563]       Time  0.132 ( 0.308)    Loss 5.6573e-01 (9.9941e-01)    Acc@1  84.38 ( 75.02)   Acc@5 100.00 ( 92.22)
Test: [1500/1563]       Time  0.470 ( 0.297)    Loss 1.3907e+00 (1.0010e+00)    Acc@1  65.62 ( 74.95)   Acc@5  87.50 ( 92.25)
 * Acc@1 74.854 Acc@5 92.232
这是trt的结果：
 47800 ==> * Acc@1 19.198 Acc@5 33.041
 47900 ==> * Acc@1 19.204 Acc@5 33.035
 48000 ==> * Acc@1 19.193 Acc@5 33.003
 48100 ==> * Acc@1 19.185 Acc@5 32.993
 48200 ==> * Acc@1 19.155 Acc@5 32.947
 48300 ==> * Acc@1 19.122 Acc@5 32.898
 48400 ==> * Acc@1 19.117 Acc@5 32.908
 48500 ==> * Acc@1 19.080 Acc@5 32.849
 48600 ==> * Acc@1 19.065 Acc@5 32.831
 48700 ==> * Acc@1 19.069 Acc@5 32.829
 48800 ==> * Acc@1 19.043 Acc@5 32.784
 48900 ==> * Acc@1 19.016 Acc@5 32.756
 49000 ==> * Acc@1 19.024 Acc@5 32.752
 49100 ==> * Acc@1 19.012 Acc@5 32.722
 49200 ==> * Acc@1 19.044 Acc@5 32.739
 49300 ==> * Acc@1 19.010 Acc@5 32.679
 49400 ==> * Acc@1 19.008 Acc@5 32.657
 49500 ==> * Acc@1 19.030 Acc@5 32.674
 49600 ==> * Acc@1 19.028 Acc@5 32.665
 49700 ==> * Acc@1 19.042 Acc@5 32.694
 49800 ==> * Acc@1 19.026 Acc@5 32.668
 49900 ==> * Acc@1 19.006 Acc@5 32.647
 Final ==> * Acc@1 18.970 Acc@5 32.590

**Comment by shijie-nv** [comment]
@HawkL327 
你的意思是训练时log输出结果正常，导出后在推理引擎的结果很差是吧。

我遇到类似的问题。官方样例里面，用到的两个backend (Tengine_u8 和 tensorrt）现在都跑不通了。
我觉得deploy代码有些问题，能否修复一下 @Tracin

**Comment by HawkL327** [comment]
> @HawkL327 你的意思是训练时log输出结果正常，导出后在推理引擎的结果很差是吧。
> 
> 我遇到类似的问题。官方样例里面，用到的两个backend (Tengine_u8 和 tensorrt）现在都跑不通了。 我觉得deploy代码有些问题，能否修复一下 @Tracin

是的

**Comment by YeRen123455** [comment]
@HawkL327  @shijie001 两位大佬问题解决了嘛，我也遇到精度下降问题。
