### ISSUE TITLE
如果我想取消掉某个算子的量化应该怎么做?

### ISSUE THREAD

**Issue by HawkL327** [ModelTC/MQBench#174]
比如trt后端，我不希望upsample做int8计算，试了把module_type_to_quant_input里面的upsample注释掉，还是会被量化

**Comment by Tracin** [comment]
https://github.com/ModelTC/MQBench/blob/main/mqbench/custom_quantizer/model_quantizer.py#L205

**Comment by HawkL327** [comment]
> https://github.com/ModelTC/MQBench/blob/main/mqbench/custom_quantizer/model_quantizer.py#L205

请问 add和mul呢
