### ISSUE TITLE
如何用tvm运行ONNX_QNN导出的onnx模型

### ISSUE THREAD

**Issue by damon-93** [ModelTC/MQBench#175]
您好：我把模型backend = BackendType.ONNX_QNN并使用convert_deploy函数导出onnx模型，我想ONNX_QNN格式是给tvm前向推理使用的吧
我在 https://mqbench.readthedocs.io/en/latest/user_guide/howtodeploy.html  并没有找到tvm对应的例子
所以我的问题是：
1.ONNX_QNN格式是给tvm前向推理使用的吗？
2.基于第1点，能给tvm加载使用ONNX_QNN前向推理的例子吗？或者给个学习资料的链接也行

非常感谢
另外：我觉得MQBench非常好使，QAT后我在TensorRT上用起来了，精度牛逼,速度飞起~

**Comment by Tracin** [comment]
https://tvm.apache.org/docs/how_to/compile_models/from_onnx.html

**Comment by damon-93** [comment]
非常感谢您的回复，我按例子中的方式加载QNN的onnx模型，但是报错如下
```
tvm.error.OpNotImplemented: The following operators are not supported for frontend ONNX: QLinearConv, QLinearGlobalAveragePool, QLinearAdd
```
应该是tvm不支持这些算子层，我导出的QNN同样不能用onnxruntime运行
是我在导出QNN的时候就错了吗？QNN模型如下:

![image](https://user-images.githubusercontent.com/32932670/185567907-52ef247f-06bb-4b7f-9e42-138dd8270acb.png)



TVM加载QNN模型代码如下:
```
target = tvm.target.cuda(model='3090')
input_name = "input"
shape_dict = {input_name: (1,3,224,224)}
model_path="./resnet18_qat_tvm_e0_0.9504549050632911.onnx.onnx"
onnx_model = onnx.load(model_path)
mod, params = relay.frontend.from_onnx(onnx_model, shape_dict)
```

**Comment by Tracin** [comment]
https://github.com/apache/tvm/blob/main/python/tvm/relay/frontend/onnx.py#L4198

**Comment by damon-93** [comment]
@Tracin  
非常感谢回复，上面QLinearConv等算子问题是因为我用的tvm板本太低了,这个问题解决了
我遇到了新的问题：在调用relay.frontend.from_onnx函数时遇到
```
An error occurred during the execution of TVM.
For more information, please see: https://tvm.apache.org/docs/errors.html
---------------------------------------------------------------
  Check failed: (false) is false: [17:41:25] /data/xiaojun/tvm/src/relay/qnn/op/quantize.cc:49: 
---------------------------------------------------------------
An error occurred during the execution of TVM.
For more information, please see: https://tvm.apache.org/docs/errors.html
---------------------------------------------------------------
  Check failed: (input_dtype == DataType::Float(32)) is false: Input type should be one of float32 but was uint8
```

![image](https://user-images.githubusercontent.com/32932670/185892528-7c5289a9-f047-4b58-9020-b48b81eda083.png)
报错位置：
![image](https://user-images.githubusercontent.com/32932670/185892795-eb2dc854-5ccd-4a8d-9c77-d087cf820184.png)

通过追踪代码发现QLinearConv能顺利通过，但是在MaxPool就会报出上述错误
看了onnx的结构确实这个MaxPool和其他层的形式有点不一致
报错代码位置,就是检查了输入数据的类型是否为Float(32)
```
tvm/src/relay/qnn/op/quantize.cc
bool QuantizeRel(const Array<Type>& types, int num_inputs, const Attrs& attrs,
                 const TypeReporter& reporter) {
                xxxxxxxxxxxxxx
                 ICHECK(input_dtype == DataType::Float(32))
      << "Input type should be one of float32 but was " << input_dtype;
                xxxxxxxxxxxxxx
```
综上：MaxPool上一层为QuantizeLinear这就会输出int8/uint8的数据，导致错误抛出？
我理解的比较浅显，您看看上述的理解是否正确，并请教一下您如何规避这个问题。

**Comment by Xrigok** [comment]
我遇到了相同的问题，在MaxPool处要求输入的是float32，但上一层输出是int8,。想请问下你解决了吗
