### ISSUE TITLE
AdaRound TensorRT Deploy

### ISSUE THREAD

**Issue by lingffff** [ModelTC/MQBench#186]
作者好，有个关于TensorRT部署的问题：

对于激活量化，截断阈值通过clip_ranges.json传给onnx2trt构建engine；
对于权重量化，TensorRT的机制应该是直接取min-max对称量化然后Round到定点，
那么，AdaRound的结果是如何作用到TensorRT的权重量化呢？

**Comment by Tracin** [comment]
可以手动计算`weight * (127 / abs(max))` 就可以发现结果无需round就是定点数

**Comment by lingffff** [comment]
OK 但实际上TensorRT量化权重的时候还是有Round（四舍五入）这一步的是吧？只是在做AdaRound的时候把原来的浮点权重调整到了与`weight * (127 / abs(max))`对应的相同值上

**Comment by Tracin** [comment]
> OK 但实际上TensorRT量化权重的时候还是有Round（四舍五入）这一步的是吧？只是在做AdaRound的时候把原来的浮点权重调整到了与`weight * (127 / abs(max))`对应的相同值上

是的

**Comment by lingffff** [comment]
Thanks a lot.
