### ISSUE TITLE
How to deploy it with tensorRT

### ISSUE THREAD

**Issue by KevenLee** [ModelTC/MQBench#19]
thanks for your great jobs!

But how to deploy this quantified  model and params to tensorRT

**Comment by KevenLee** [comment]
could you share some demos?

**Comment by Tracin** [comment]
https://github.com/ModelTC/MQBench/blob/master/application/imagenet_example/readme.md

**Comment by KevenLee** [comment]
> https://github.com/ModelTC/MQBench/blob/master/application/imagenet_example/readme.md

thanks for your reply.
