### ISSUE TITLE
NameError: module is not installed as a submodule

### ISSUE THREAD

**Issue by bobby20180331** [ModelTC/MQBench#192]
I use mqbench for just  tracing.  However,problem accur. 
code :
     ...
     model.eval()
    ## fx 
    # backend = BackendType.Tensorrt
    backend = BackendType.ONNX_QNN
    model = prepare_by_platform(model, backend)   

exception:

line 47, in forward
    img_feat_multiscale.append(torch.nn.Upsample(size=(56, 56), mode='bilinear')(x))
  File "/root/anaconda3/envs/c2ffxt18/lib/python3.7/site-packages/torch/fx/_symbolic_trace.py", line 604, in module_call_wrapper
    return self.call_module(mod, forward, args, kwargs)
  File "/root/anaconda3/envs/c2ffxt18/lib/python3.7/site-packages/torch/fx/_symbolic_trace.py", line 420, in call_module
    module_qualified_name = self.path_of_module(m)
  File "/root/anaconda3/envs/c2ffxt18/lib/python3.7/site-packages/torch/fx/_symbolic_trace.py", line 381, in path_of_module
    raise NameError('module is not installed as a submodule')
NameError: module is not installed as a submodule

**Comment by aksenventwo** [comment]
这是构建模型的问题 `img_feat_multiscale.append(torch.nn.Upsample(size=(56, 56), mode='bilinear')(x))` 这种方式构建模型是不会把 `torch.nn.Upsample(size=(56, 56), mode='bilinear')` 注册到 model 里面的 `modules` 的，但是 torch.fx  trace 时又跟踪到了这个调用，所以你需要把这个替换成 `self.up = torch.nn.Upsample(size=(56, 56), mode='bilinear')`，它会自动加入到 model 里面里面的 `modules` ， 然后用 `self.up(x)` 来调用就不会报这个错了。

**Comment by bobby20180331** [comment]
Thanks a lot .It seems worked.
