### ISSUE TITLE
WARNING: The shape inference of ::LearnablePerTensorAffine type is missing

### ISSUE THREAD

**Issue by bobby20180331** [ModelTC/MQBench#194]
WARNING: The shape inference of ::LearnablePerTensorAffine type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
when I use: 

input_shape={'data': [1, 3, 224, 224]}
convert_deploy(model, BackendType.ONNX_QNN, input_shape)

can we ignore this warning ?

**Comment by bobby20180331** [comment]
And  Then I got an error.

Traceback (most recent call last):
  File "inference_fx.py", line 280, in <module>
    main(args)
  File "inference_fx.py", line 80, in main
    run_evaluation(model, data_loader_eval, device, args)
  File "inference_fx.py", line 141, in run_evaluation
    c_result=convert_deploy(model, BackendType.ONNX_QNN, input_shape)
  File "/root/anaconda3/envs/c2ffxt18/lib/python3.7/site-packages/MQBench-0.0.6-py3.7.egg/mqbench/convert_deploy.py", line 184, in convert_deploy
    convert_function(deploy_model, **kwargs)
  File "/root/anaconda3/envs/c2ffxt18/lib/python3.7/site-packages/MQBench-0.0.6-py3.7.egg/mqbench/convert_deploy.py", line 138, in deploy_qparams_tvm
    ONNXQNNPass(onnx_model_path).run(model_name)
  File "/root/anaconda3/envs/c2ffxt18/lib/python3.7/site-packages/MQBench-0.0.6-py3.7.egg/mqbench/deploy/deploy_onnx_qnn.py", line 277, in run
    self.replace_op_pass()
  File "/root/anaconda3/envs/c2ffxt18/lib/python3.7/site-packages/MQBench-0.0.6-py3.7.egg/mqbench/deploy/deploy_onnx_qnn.py", line 187, in replace_op_pass
    self.replace_add_to_qlinearadd(node, idx)
  File "/root/anaconda3/envs/c2ffxt18/lib/python3.7/site-packages/MQBench-0.0.6-py3.7.egg/mqbench/deploy/deploy_onnx_qnn.py", line 119, in replace_add_to_qlinearadd
    assert first_input_node.op_type in FAKE_QUANTIZE_OP
AssertionError

I have traced the vars  value as followed:
first_input_node.op_type:Mul
FAKE_QUANTIZE_OP: ['FakeQuantizeLearnablePerchannelAffine', 'FixedPerChannelAffine', 'FakeQuantizeDSQPerchannel', 'LearnablePerTensorAffine', 'FixedPerTensorAffine', 'FakeQuantizeDSQPertensor']

**Comment by zmzds** [comment]
请问你解决了吗？我也遇到这个问题了

**Comment by YeRen123455** [comment]
@zmzds @bobby20180331  请问你们解决上面的问题了吗，我一直复现不出来example里面的ImageNet的例子，怀疑是转ONNX的时候，这个Error导致的问题。

**Comment by jmkho** [comment]
Hi, I also encountered this problem except mine returns several types of error
```
WARNING: The shape inference of ::FixedPerTensorAffine type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding 
it in symbolic function.
WARNING: The shape inference of ::FixedPerChannelAffine type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding
 it in symbolic function.
```

Any idea as to why this happened and how to solve them? Thanks!

**Comment by PannenetsF** [comment]
> Hi, I also encountered this problem except mine returns several types of error
> 
> ```
> WARNING: The shape inference of ::FixedPerTensorAffine type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding 
> it in symbolic function.
> WARNING: The shape inference of ::FixedPerChannelAffine type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding
>  it in symbolic function.
> ```
> 
> Any idea as to why this happened and how to solve them? Thanks!

You should disable the fake quantize in the export stage, as there are no implementations in the onnx. The MQBench processes the weight to onnx and activation to some jsons.

**Comment by Zhuyixuan519** [comment]
> > Hi, I also encountered this problem except mine returns several types of error
> > ```
> > WARNING: The shape inference of ::FixedPerTensorAffine type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding 
> > it in symbolic function.
> > WARNING: The shape inference of ::FixedPerChannelAffine type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding
> >  it in symbolic function.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Any idea as to why this happened and how to solve them? Thanks!
> 
> You should disable the fake quantize in the export stage, as there are no implementations in the onnx. The MQBench processes the weight to onnx and activation to some jsons.

Hi, may I ask how to disable the fake-quantize? Is there any config or setting can we set? Thanks!
