### ISSUE TITLE
请问，当前MQBench量化工具中的NNIE量化算法是否支持生成的模型部署在海思芯片上？

### ISSUE THREAD

**Issue by tensorflowt** [ModelTC/MQBench#197]
你好！

目前海思芯片仅支持caffe框架，模型的移植流程为：pytorch-》onnx-》caffe-量化--》wk。

想咨询一下，通过MQBench量化工具中的NNIE量化算法是否可以实现生成的pytorch模型：

pytorch->onnx->caffe->wk

即，MQBench量化工具的NNIE量化算法替换了海思的量化算法。

**Comment by Tracin** [comment]
海思芯片需要将量化参数以特定编码方式写入wk中,我不确定编码格式是否能够开源,

**Comment by tensorflowt** [comment]
> 海思芯片需要将量化参数以特定编码方式写入wk中,我不确定编码格式是否能够开源,

![MQBench](https://user-images.githubusercontent.com/37217594/192549382-8b408dda-7611-4fff-8688-bcd009dd11e2.png)

如上图，箭头所指的为删除量化节点以便部署到真实硬件上。
我是否可以理解为，经过MQBench量化后的模型权重，经过删除量化节点并将对应的量化参数以特定编码方式写入wk中就可以实现量化参数替换了呢？

**Comment by XHPlus** [comment]
> > 海思芯片需要将量化参数以特定编码方式写入wk中,我不确定编码格式是否能够开源,
> 
> ![MQBench](https://user-images.githubusercontent.com/37217594/192549382-8b408dda-7611-4fff-8688-bcd009dd11e2.png)
> 
> 如上图，箭头所指的为删除量化节点以便部署到真实硬件上。 我是否可以理解为，经过MQBench量化后的模型权重，经过删除量化节点并将对应的量化参数以特定编码方式写入wk中就可以实现量化参数替换了呢？

是的。需要将量化参数编码成NNIE的格式写入进去。
