### ISSUE TITLE
not compatible with pytorch 1.9+

### ISSUE THREAD

**Issue by mikeseven** [ModelTC/MQBench#20]
FX was really experimental in torch 1.8 and it has significantly been upgraded.
Any plan to update MQBench to be compatible with pytorch 1.9 and up?

**Comment by Tracin** [comment]
FX become stable in 1.10, we consider update this project based on 1.10 ASAP.

**Comment by mikeseven** [comment]
Main-dev branch works with 1.10 but not 1.11...
