### ISSUE TITLE
关于Brecq的问题

### ISSUE THREAD

**Issue by LHH20000923** [ModelTC/MQBench#201]
![1](https://user-images.githubusercontent.com/83012544/193004700-6bf2abc7-1e95-47a9-be77-a8724f6350c5.png)

我使用Brecq算法时，代码重建最右边256x512x1x1的卷积时，the node会选择左侧的分支而不会选择右边的分支作为block。请问这个要怎么解决？

**Comment by PannenetsF** [comment]
可以提供一份最小代码，近期我check一下

**Comment by LHH20000923** [comment]
[代码.zip](https://github.com/ModelTC/MQBench/files/9680356/default.zip)
这是我的网络结构代码
