### ISSUE TITLE
Backend选择ONNX_QNN， convert_deploy  error

### ISSUE THREAD

**Issue by crleagure** [ModelTC/MQBench#203]
我实验中Backend选择ONNX_QNN， weight 设置为 perchannel，asymmetric；activation 设置为perlayer， symmetric;
模型收敛后，调用convert_deploy报错，错误出现位置是因为：
 weight的op_type是FakeQunatizeLearnablePerchannelAffine类型，这个node里面input只有3个（weight, scale,zero_point）,
这就导致deploy_onnx_qnn.py文件的第261行代码：
scale，zero_point, qmin, qmax = node.input[1],node.input[2],node.input[3],node.input[4]
直接越界，这个该怎么修改

**Comment by Tracin** [comment]
https://github.com/ModelTC/MQBench/blob/main/mqbench/fake_quantize/lsq.py#L102-L110
尝试把L110修改成
`return g.op("::FakeQuantizeLearnablePerchannelAffine", x, scale, zero_point, quant_min, quant_max)`

**Comment by crleagure** [comment]
> https://github.com/ModelTC/MQBench/blob/main/mqbench/fake_quantize/lsq.py#L102-L110 尝试把L110修改成 `return g.op("::FakeQuantizeLearnablePerchannelAffine", x, scale, zero_point, quant_min, quant_max)`

好的，我试一下

**Comment by crleagure** [comment]
> https://github.com/ModelTC/MQBench/blob/main/mqbench/fake_quantize/lsq.py#L102-L110 尝试把L110修改成 `return g.op("::FakeQuantizeLearnablePerchannelAffine", x, scale, zero_point, quant_min, quant_max)`

你好，我这边还想请教两个问题：

1. Backend选择ONNX_QNN，在deploy_onnx_qnn.py文件的merge_relu_pass函数中，为啥scale=min(scale, 6.0 / 255), 没太理解这行代码，也不清楚6是咋来的

2. 目前是不是还不支持conv_tranpose反卷积的量化

**Comment by Tracin** [comment]
1. Clip目前当作Relu6使用
2. ONNX opset里似乎还没有QinearConvTranspose算子

**Comment by crleagure** [comment]
> 1. Clip目前当作Relu6使用
> 2. ONNX opset里似乎还没有QinearConvTranspose算子

这样的话，我基本上明白了，多谢
