### ISSUE TITLE
请问，有什么办法能缓解QAT带来的显存占用过多问题吗

### ISSUE THREAD

**Issue by Menace-Dragon** [ModelTC/MQBench#204]
在Imagenet_example项目下，我跑Res18 training 单卡时显存占4300M左右;而Res18 QAT training时单卡共占9400M左右。也就是说插入了量化节点大约带来了将近一倍的显存占用，有什么办法能稍微缓解QAT时显存开销大的问题吗😭

**Comment by Tracin** [comment]
量化节点应该不会有这么大, 能够进一步分析显存的分配占比吗? Model size / Data size / Grad size / Optimizer size ?

**Comment by Tracin** [comment]
Res18 bs=128 SGD

- FP模型 4900M 模型+数据+weight所需梯度变量
- 使用FixedFakeQuantize(scale / zero_point不进行学习, 不获取梯度, 不保留中间变量) 7400M
- 使用LeanrableFakeQuantize(scale / zero_point获取梯度, 保留中间变量) 9400M
