### ISSUE TITLE
LSQ反向梯度更新

### ISSUE THREAD

**Issue by crleagure** [ModelTC/MQBench#206]
你好，我想请教下，lsq的scale和zeropoint的反向传播的梯度更新在哪实现的，
我看代码中只写了forward和symbolic，但是没有实现backward

**Comment by Tracin** [comment]
Torch自动求导

**Comment by crleagure** [comment]
你好，我想请教下，为啥基于mqbench对pytorch官方的mobilenet v2做PTQ量化，per-channel的方式效果很差，都没有per-layer的好



| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年10月17日 13:48 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [ModelTC/MQBench] LSQ反向梯度更新 (Issue #206) |

Torch自动求导
