### ISSUE TITLE
YOLOX经过QAT训练后导入Tengine 量化精度奔溃

### ISSUE THREAD

**Issue by RedHandLM** [ModelTC/MQBench#208]
问题描述：
1： 基于UP使用YOLOX进行fp32训练，map=0.52，fp32 pth使用toonnx脚本导出onnx，精度无掉点
2： 基于UP使用YOLOX进行QAT训练，map=0.52
3:    使用python -u -m up quant_deploy  --config=$cfg 导出 qat onnx和scale
4： 将onnx转换为tmfile，然后使用tengine后量化工具导入 scale 对模型进行量化，uint8模型精度崩溃无bbox输出
      
针对qat导出的onnx做了以下试验：
验证1：qat deploy导出的onnx，直接使用py推理，精度正常
验证2： qat deploy导出的onnx，直接走tengine量化流程，不导入scale，使用校验集进行uint8量化，精度降低10个点，但是有bbox输出

现在导入scale uint8的精度就崩溃，希望排查下看是scale 文件的问题还是哪里的问题？

       
以下是训练和导出环境：
```
MQBench                 0.0.6
UP                      0.3.0
PyTorch version: 1.10.0+cu111
Is debug build: False
CUDA used to build PyTorch: 11.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.4 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.20.6
Libc version: glibc-2.31

Python version: 3.8.13 (default, Mar 28 2022, 11:38:47)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.15.0-46-generic-x86_64-with-glibc2.17
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 3060
Nvidia driver version: 470.141.03
```

==============以下是使用的yolox 配置文件==============
yolox 训练fp32模型 ： base_yolox_s_ret_a1_comloc.yaml  
导出fp32 onnx模型：    toonnx_base_yolox_s_ret_a1_comloc.yaml
yolox 训练qat模型：  base_yolox_s_ret_a1_comloc_quant_tengine_qat.yaml
导出qat模型：  deploy_qat_base_yolox_s_ret_a1_comloc_quant_tengine_qat.yaml
[config.zip](https://github.com/ModelTC/MQBench/files/9826341/config.zip)

==============以下是各个阶段的模型文件==============
链接: https://pan.baidu.com/s/1-KFP1xZq94HwzalrgzwIkA  密码: 28ei
--来自百度网盘超级会员V4的分享

**Comment by XHPlus** [comment]
@un-knight Hi Junxian, do you have some suggestions for debugging this problem?

**Comment by RedHandLM** [comment]
@un-knight 基于tengine中的工具algin_with_onnx，使用qat deploy导出的onnx和基于导入的scale 量化出的tmfile进行对齐，
![onnx_tmfile_algin_base_pic](https://user-images.githubusercontent.com/17703818/197143422-0a400561-8546-4d19-8c55-2f61efd9fae2.png)
从结果可以看出，cls分支和iou分支正常，但是bbox分支差异较大，左边文件三列分别是 层名,L1_DISTANCE , L2_DISTANCE

**Comment by RedHandLM** [comment]
增加tengine  quant_util_uint8可执行文件, 指定qat导出的scale文件进行量化模型时输出的cosin日志，较多层输出为nan，出现明显精度崩溃
[log.txt](https://github.com/ModelTC/MQBench/files/9837810/log.txt)

**Comment by un-knight** [comment]
@RedHandLM The uint8 `sigmoid` operator of tengine is not aligned in https://github.com/ModelTC/MQBench/pull/172, but a fake quantization node is added for `sigmoid` in mqbench as a work around. The calculation of the head part of YOLOX is more complicated because of all the complicated non-linear operators. It is recommended that check the consistency for the backbone firstly. If there is no consistency problem with backbone , there may be a problem with the non-linear operators in the head part.

**Comment by RedHandLM** [comment]
@un-knight 现在导出的onnx模型都是只有backbone的，不包含head 和 decode
![image](https://user-images.githubusercontent.com/17703818/197440399-5ef4dd37-9bf0-4a61-a9d3-3421d3dd5b73.png)
量化后精度仍然是崩溃，但是我用resnet的最小代码块尝试了，没有出现cosin为nan的情况，是不是yolox里面的一些特殊算子导致的？我尝试从quant_util_uint8输出的cosin 值中找到精度崩溃的层，但是只看到一个普通的conv，没有什么特殊

**Comment by RedHandLM** [comment]
左边是用test_quantize_tengine_u8 导出onnx然后导入scale进行量化出来的cosin日志，右边是yolox的日志，明显能看到yolox的cosin值大部分是nan，有精度崩溃
![1](https://user-images.githubusercontent.com/17703818/197440994-c57f5224-217d-460a-8d8c-df56dc641b06.png)

**Comment by RedHandLM** [comment]
yolox nan日志如下：
[log.txt](https://github.com/ModelTC/MQBench/files/9848527/log.txt)

**Comment by un-knight** [comment]
> @un-knight 现在导出的onnx模型都是只有backbone的，不包含head 和 decode ![image](https://user-images.githubusercontent.com/17703818/197440399-5ef4dd37-9bf0-4a61-a9d3-3421d3dd5b73.png) 量化后精度仍然是崩溃，但是我用resnet的最小代码块尝试了，没有出现cosin为nan的情况，是不是yolox里面的一些特殊算子导致的？我尝试从quant_util_uint8输出的cosin 值中找到精度崩溃的层，但是只看到一个普通的conv，没有什么特殊

@RedHandLM 有两个建议，第一，tengine uint8 backend不支持swish算子，可参考这篇有介绍如何使用tengine部署YOLOX：https://zhuanlan.zhihu.com/p/392387835；第二，可以造一个conv+swish的小模型，帮助定位问题。

**Comment by RedHandLM** [comment]
@un-knight 你好，算子问题上周我已经更改过了，新的算子使用hardsigmoid, 从fp32重新开始训练，然后再qat，再导出，问题仍然没有解决，另外我们走通了tengine的uint8流程，导出的qat模型直接使用图片量化可以得到正确结果，一旦使用scale精度就崩溃，另外还尝试了将conv的卷积从per channel改成per tensor以支持npu，同样没有解决，目前还有什么排查方向么

**Comment by RedHandLM** [comment]
![image](https://user-images.githubusercontent.com/17703818/198917084-25294c77-c495-42aa-aefb-1f92278fd753.png)

**Comment by un-knight** [comment]
> @un-knight 你好，算子问题上周我已经更改过了，新的算子使用hardsigmoid, 从fp32重新开始训练，然后再qat，再导出，问题仍然没有解决，另外我们走通了tengine的uint8流程，导出的qat模型直接使用图片量化可以得到正确结果，一旦使用scale精度就崩溃，另外还尝试了将conv的卷积从per channel改成per tensor以支持npu，同样没有解决，目前还有什么排查方向么

@RedHandLM 建议先造一个conv+hardswish的简单block，从QAT到tengine uint8 backend tmfile，对比下一致性差异。
