### ISSUE TITLE
ConvTranspose2d in Adaround

### ISSUE THREAD

**Issue by jmliu206** [ModelTC/MQBench#210]
When I use Adaround to quantize my model, it seems that it is useless to the convtransposed2d.
I check advanced_ptq.py, there is no support for  convtransposed2d.

```
_ADAROUND_SUPPORT_TYPE = (torch.nn.Conv2d, torch.nn.Linear)
_FUSED_TYPE = (nniqat.ConvBnReLU2d, nniqat.ConvBn2d, qnniqat.ConvFreezebn2d, qnniqat.ConvFreezebnReLU2d)
_WEIGHTS_MODULE_TYPE = (torch.nn.Conv2d, torch.nn.Linear)
```

Could I know how to utilize adaround for convtransposed2d?

**Comment by Tracin** [comment]
Update _ADAROUND_SUPPORT_TYPE and add convtransposed2d in it.
See if any further error occurs...

**Comment by jmliu206** [comment]
Thanks, it works
