### ISSUE TITLE
Does MQBench supports Advanced PTQ on the transformer model?

### ISSUE THREAD

**Issue by hobbitlzy** [ModelTC/MQBench#215]
The transformer model seems not to support layer-wisely finetuning on the calibration dataset. Will this feature be supported？

**Comment by Tracin** [comment]
How about this **https://github.com/ModelTC/MQBench/tree/main/application/nlp_example**

**Comment by hobbitlzy** [comment]
I'm sorry I didn't make it clear. Can the transformer model be finetuned using the AdaRound-like algorithm?
