### ISSUE TITLE
关于如何将conv和bn层进行合并的问题

### ISSUE THREAD

**Issue by xiaopengaia** [ModelTC/MQBench#218]
嗨 大家好，

今天在做resnet50量化的时候，想将conv层和bn层进行合并，然后进行量化

为此我找到了`fuser_method_mappings.py`这个文件

同时调用了`fuse_conv_freezebn`这个函数

但在进行合并的时候，发现需要将网络中的conv和bn单独提取处理来，进行合并

显然，这样操作似乎过于麻烦些

因此，我尝试寻找r50_8_8.yaml中能够针对conv和bn相互融合的参数，未果

想请教大家是如何合并bn和conv层的

有没有较好的简便的方法，或者在r50_8_8.yaml是否有参数能够进行处理呢？

希望得到指正，谢谢大家！

**Comment by aksenventwo** [comment]
转换模型后在进行校准或者训练前可以调用这个方法https://github.com/ModelTC/MQBench/blob/835b48e8542b81a1989e08d8f31878655687ffc7/mqbench/convert_deploy.py#L35

**Comment by xiaopengaia** [comment]
非常感谢您的回复。我尝试下。
