### ISSUE TITLE
Why save the clip_range of weights in tensorrt deployment?

### ISSUE THREAD

**Issue by KeyKy** [ModelTC/MQBench#22]
I find you only save and set the clip_range of activation when deploying in backend tensorrt. For the weights of models, you only clip them. tensorrt do not need to quantize weights of convolution?

**Comment by XHPlus** [comment]
This is because TensorRT does not provide API to set clipping range for weight. And for weight, we can clip the weight in advance if needed. So the weight range does not need to be saved

**Comment by KeyKy** [comment]
OK，thanks.
