### ISSUE TITLE
关于yolov5s进行PTQ量化出现TraceError问题

### ISSUE THREAD

**Issue by xiaopengaia** [ModelTC/MQBench#220]
嗨 大家好，

今天我尝试使用mqbench对yolov5s进行PTQ量化

yolov5s模型来自于：https://github.com/ultralytics/yolov5.git

当我尝试如下代码进行yolov5s量化处理时

```python
from mqbench.prepare_by_platform import prepare_by_platform, BackendType

backend = BackendType.ONNX_QNN
model = prepare_by_platform(model, backend)
```

出现了这个问题

```shell
torch.fx.proxy.TraceError: symbolically traced variables cannot be used as inputs to control flow
```

请问大家，这个问题有什么好的，简便的方式处理呢？

**Comment by aksenventwo** [comment]
可以看看 #82

**Comment by xiaopengaia** [comment]
好的，非常感谢，这个对我很有帮助

**Comment by huangweiwh** [comment]
> 嗨 大家好，
> 
> 今天我尝试使用mqbench对yolov5s进行PTQ量化
> 
> yolov5s模型来自于：https://github.com/ultralytics/yolov5.git
> 
> 当我尝试如下代码进行yolov5s量化处理时
> 
> ```python
> from mqbench.prepare_by_platform import prepare_by_platform, BackendType
> 
> backend = BackendType.ONNX_QNN
> model = prepare_by_platform(model, backend)
> ```
> 
> 出现了这个问题
> 
> ```shell
> torch.fx.proxy.TraceError: symbolically traced variables cannot be used as inputs to control flow
> ```
> 
> 请问大家，这个问题有什么好的，简便的方式处理呢？

您好，请问您解决这个问题了吗

**Comment by dengxiongshi** [comment]
Have anyone solved it?
