### ISSUE TITLE
2-bit LSQ quantization on ResNet18

### ISSUE THREAD

**Issue by CYang0515** [ModelTC/MQBench#23]
Hi,
Is there 2-bit LSQ quantization config parameters on ResNet18? I use the [config](https://github.com/ModelTC/MQBench/blob/3f8321ec9ab9fd05d99c21700a901b1ff6a90a1e/application/lsq_configs/resnet18-4bit-acedemic.yaml) and change the quantization bits to 2 and keep others same, and get 65.508 top1 accuracy. There is about 2.1% gap compared with 67.6 in original LSQ paper. Can you give me some advices to reproduce the results?
Thanks.

**Comment by HXuan-Wang** [comment]
Hello, have you solved this problem. I have the same problem
