### ISSUE TITLE
onnx qnn 部署模型问题

### ISSUE THREAD

**Issue by wangshankun** [ModelTC/MQBench#231]
官方给的resnet50里面，QLinearConv 是包含了QuantizeLinear 
![image](https://user-images.githubusercontent.com/3970271/217719324-9c27db6e-7854-4884-ab45-0d98a80a152e.png)

而mqbench convert的模型中：多了一个QuantizeLinear ，
![image](https://user-images.githubusercontent.com/3970271/217719434-e4169aed-5b13-407e-b986-20919468d6dc.png)

因为QuantizeLinear 输入是int32或者float的，这会导致onn qnn convert出来的模型不能用：

![image](https://user-images.githubusercontent.com/3970271/217719622-dd9c91d3-ecae-49fe-ae44-7e65388d5418.png)

**Comment by Tracin** [comment]
这里应该是DequantizeLinear

**Comment by wangshankun** [comment]
> 

嗯，不过maxpool也能支持uint8/int8吧，我把maxpool放到了qlinear_op_type里面，算是暂时绕开这个错误；

另外，onnx已经支持FC了，量化算子是QLinearMatMul； onnx_qnn应该要把这个算子加上了吧？

**Comment by Tracin** [comment]
> > 
> 
> 嗯，不过maxpool也能支持uint8/int8吧，我把maxpool放到了qlinear_op_type里面，算是暂时绕开这个错误；
> 
> 另外，onnx已经支持FC了，量化算子是QLinearMatMul； onnx_qnn应该要把这个算子加上了吧？

QLinearMatMul不完全是FC, 因为缺少bias add操作.

**Comment by wangshankun** [comment]
> 
是的，但是onnx官方用QLinearMatMul + QLinearAdd方式实现的
![image](https://user-images.githubusercontent.com/3970271/217759508-63f4f8fe-1af2-4ba8-828f-fa9e9c3eafa5.png)

或者用卷积代替

**Comment by Tracin** [comment]
是的, Pytorch实现的难点是无法统计MatMul和Add中间Tensor的数值范围, 给ONNX提了QLinearFC的[issue](https://github.com/microsoft/onnxruntime/issues/9642).

**Comment by wangshankun** [comment]
> 是的, Pytorch实现的难点是无法统计MatMul和Add中间Tensor的数值范围, 给ONNX提了QLinearFC的[issue](https://github.com/microsoft/onnxruntime/issues/9642).

Add要求bias 8bit，这个有点不符合部署实情，那我还是在deploy_onnx_qnn里面用1x1卷积代替FC吧；
别的不说，至少resnet18和50得支持了吧

FC变成1*1卷积，再和reshape掉个顺序就成了
![image](https://user-images.githubusercontent.com/3970271/217821661-95efbf3e-8714-439a-9dd2-82fd4ffbf892.png)
