### ISSUE TITLE
关于混合精度mixed-precision量化的支持和bug问题

### ISSUE THREAD

**Issue by Tlinn7** [ModelTC/MQBench#238]
你好最近在尝试使用MQbench的混合量化调试时，遇到几个问题想请教一下~

1. 从脚本看，MQbench目前是支持混合精度的是吗？也就是通过hessian矩阵就算每层的量化敏感度信息，最后能通过计算得到每一层具体的量化比特数建议，对吗？有没有一些公开的信息去介绍？

非常感谢~

**Comment by wimh966** [comment]
你好，是的，目前支持混合精度，能通过计算得到每一层具体的量化比特数建议。具体的算法信息可以参考论文HAWQ。

**Comment by Alicture** [comment]
any update on this issue?
