### ISSUE TITLE
Some problems about using MQBench tool in YOLOv5

### ISSUE THREAD

**Issue by Joejwu** [ModelTC/MQBench#24]
First, thanks for your work!
And when i use the MQBench tool in YOLOv5, I made some changes to the code of YOLOv5 according to the instructions in the documents, bur when I was training, I found that the speed of training was so slow.
So I would like to ask whether this situation is normal or whether I need to continue to optimize something! Looking forward to your reply! Thanks!
![image](https://user-images.githubusercontent.com/46843978/144050501-c8a547b6-ad8c-487c-a8a2-adafa3f47fb5.png)
![image](https://user-images.githubusercontent.com/46843978/144050602-30c52ed4-6f97-461e-84b1-9a7857025f3e.png)

**Comment by Tracin** [comment]
Try use FixedFakeQuantizer, find if it is faster.

**Comment by yy2yy** [comment]
> First, thanks for your work! And when i use the MQBench tool in YOLOv5, I made some changes to the code of YOLOv5 according to the instructions in the documents, bur when I was training, I found that the speed of training was so slow. So I would like to ask whether this situation is normal or whether I need to continue to optimize something! Looking forward to your reply! Thanks! ![image](https://user-images.githubusercontent.com/46843978/144050501-c8a547b6-ad8c-487c-a8a2-adafa3f47fb5.png) ![image](https://user-images.githubusercontent.com/46843978/144050602-30c52ed4-6f97-461e-84b1-9a7857025f3e.png)

你好，请问你是用的什么硬件平台量化训练的，最后有没有量化训练成功？我想向您请教一下。我的qq:921785514

**Comment by www516717402** [comment]
@yy2yy 我做了一些实验（修改了微量的mqbench代码）
环境：torch-1.9.1+cuda10.2，mmcls/mmdet框架
TRT：分类模型train、test、deploy都可以。yolox训练和测试均效果很差，而且无法对齐。yolov3可以训练和模拟前向推理，trt-int8推理很差，精度无法对齐。
QNN：mmcls可行，mmdet训练可以，但转换失败。
总结：这个库不知道是否继续维护，bug修复遥遥无期。。。还不如直接PQT来的实在
