### ISSUE TITLE
PTQ后转TVM失败

### ISSUE THREAD

**Issue by Xrigok** [ModelTC/MQBench#242]
PTQ后转TVM失败：
![image](https://user-images.githubusercontent.com/31384900/228482710-79f9d898-23f1-4d33-9761-06f71874cba9.png)
在追溯的时候打印MQBench-main/mqbench/deploy/common.py里的self.graph.initializer，发现不包括对输入的伪量化节点，导致self.onnx_model.graph.node里对输入的伪量化节点在self.onnx_model.initializer里找不到。
请问下这个问题怎么解决，在qat转TVM里是包括对输入的伪量化节点，但ptq却没有，会是导出onnx的问题吗？
底下是进行PTQ时对graph.initializer的name的打印，可以发现不包括对输入的伪量化节点：
conv1.weight
conv1.bias
conv1.weight_fake_quant.scale
conv1.weight_fake_quant.zero_point
layer1.0.conv1.weight
layer1.0.conv1.bias
layer1.0.conv1.weight_fake_quant.scale
layer1.0.conv1.weight_fake_quant.zero_point
layer1.0.conv2.weight
layer1.0.conv2.bias
layer1.0.conv2.weight_fake_quant.scale
layer1.0.conv2.weight_fake_quant.zero_point
layer1.1.conv1.weight
layer1.1.conv1.bias
layer1.1.conv1.weight_fake_quant.scale
layer1.1.conv1.weight_fake_quant.zero_point
layer1.1.conv2.weight
layer1.1.conv2.bias
layer1.1.conv2.weight_fake_quant.scale
layer1.1.conv2.weight_fake_quant.zero_point
layer2.0.conv1.weight
layer2.0.conv1.bias
layer2.0.conv1.weight_fake_quant.scale
layer2.0.conv1.weight_fake_quant.zero_point
layer2.0.conv2.weight
layer2.0.conv2.bias
layer2.0.conv2.weight_fake_quant.scale
layer2.0.conv2.weight_fake_quant.zero_point
layer2.0.downsample.0.weight
layer2.0.downsample.0.bias
layer2.0.downsample.0.weight_fake_quant.scale
layer2.0.downsample.0.weight_fake_quant.zero_point
layer2.1.conv1.weight
layer2.1.conv1.bias
layer2.1.conv1.weight_fake_quant.scale
layer2.1.conv1.weight_fake_quant.zero_point
layer2.1.conv2.weight
layer2.1.conv2.bias
layer2.1.conv2.weight_fake_quant.scale
layer2.1.conv2.weight_fake_quant.zero_point
layer3.0.conv1.weight
layer3.0.conv1.bias
layer3.0.conv1.weight_fake_quant.scale
layer3.0.conv1.weight_fake_quant.zero_point
layer3.0.conv2.weight
layer3.0.conv2.bias
layer3.0.conv2.weight_fake_quant.scale
layer3.0.conv2.weight_fake_quant.zero_point
layer3.0.downsample.0.weight
layer3.0.downsample.0.bias
layer3.0.downsample.0.weight_fake_quant.scale
layer3.0.downsample.0.weight_fake_quant.zero_point
layer3.1.conv1.weight
layer3.1.conv1.bias
layer3.1.conv1.weight_fake_quant.scale
layer3.1.conv1.weight_fake_quant.zero_point
layer3.1.conv2.weight
layer3.1.conv2.bias
layer3.1.conv2.weight_fake_quant.scale
layer3.1.conv2.weight_fake_quant.zero_point
layer4.0.conv1.weight
layer4.0.conv1.bias
layer4.0.conv1.weight_fake_quant.scale
layer4.0.conv1.weight_fake_quant.zero_point
layer4.0.conv2.weight
layer4.0.conv2.bias
layer4.0.conv2.weight_fake_quant.scale
layer4.0.conv2.weight_fake_quant.zero_point
layer4.0.downsample.0.weight
layer4.0.downsample.0.bias
layer4.0.downsample.0.weight_fake_quant.scale
layer4.0.downsample.0.weight_fake_quant.zero_point
layer4.1.conv1.weight
layer4.1.conv1.bias
layer4.1.conv1.weight_fake_quant.scale
layer4.1.conv1.weight_fake_quant.zero_point
layer4.1.conv2.weight
layer4.1.conv2.bias
layer4.1.conv2.weight_fake_quant.scale
layer4.1.conv2.weight_fake_quant.zero_point
fc.weight
fc.bias
691

**Comment by MichaelXin** [comment]
您好，请问这个问题是怎么解决的？

> PTQ后转TVM失败： ![image](https://user-images.githubusercontent.com/31384900/228482710-79f9d898-23f1-4d33-9761-06f71874cba9.png) 在追溯的时候打印MQBench-main/mqbench/deploy/common.py里的self.graph.initializer，发现不包括对输入的伪量化节点，导致self.onnx_model.graph.node里对输入的伪量化节点在self.onnx_model.initializer里找不到。 请问下这个问题怎么解决，在qat转TVM里是包括对输入的伪量化节点，但ptq却没有，会是导出onnx的问题吗？ 底下是进行PTQ时对graph.initializer的name的打印，可以发现不包括对输入的伪量化节点： conv1.weight conv1.bias conv1.weight_fake_quant.scale conv1.weight_fake_quant.zero_point layer1.0.conv1.weight layer1.0.conv1.bias layer1.0.conv1.weight_fake_quant.scale layer1.0.conv1.weight_fake_quant.zero_point layer1.0.conv2.weight layer1.0.conv2.bias layer1.0.conv2.weight_fake_quant.scale layer1.0.conv2.weight_fake_quant.zero_point layer1.1.conv1.weight layer1.1.conv1.bias layer1.1.conv1.weight_fake_quant.scale layer1.1.conv1.weight_fake_quant.zero_point layer1.1.conv2.weight layer1.1.conv2.bias layer1.1.conv2.weight_fake_quant.scale layer1.1.conv2.weight_fake_quant.zero_point layer2.0.conv1.weight layer2.0.conv1.bias layer2.0.conv1.weight_fake_quant.scale layer2.0.conv1.weight_fake_quant.zero_point layer2.0.conv2.weight layer2.0.conv2.bias layer2.0.conv2.weight_fake_quant.scale layer2.0.conv2.weight_fake_quant.zero_point layer2.0.downsample.0.weight layer2.0.downsample.0.bias layer2.0.downsample.0.weight_fake_quant.scale layer2.0.downsample.0.weight_fake_quant.zero_point layer2.1.conv1.weight layer2.1.conv1.bias layer2.1.conv1.weight_fake_quant.scale layer2.1.conv1.weight_fake_quant.zero_point layer2.1.conv2.weight layer2.1.conv2.bias layer2.1.conv2.weight_fake_quant.scale layer2.1.conv2.weight_fake_quant.zero_point layer3.0.conv1.weight layer3.0.conv1.bias layer3.0.conv1.weight_fake_quant.scale layer3.0.conv1.weight_fake_quant.zero_point layer3.0.conv2.weight layer3.0.conv2.bias layer3.0.conv2.weight_fake_quant.scale layer3.0.conv2.weight_fake_quant.zero_point layer3.0.downsample.0.weight layer3.0.downsample.0.bias layer3.0.downsample.0.weight_fake_quant.scale layer3.0.downsample.0.weight_fake_quant.zero_point layer3.1.conv1.weight layer3.1.conv1.bias layer3.1.conv1.weight_fake_quant.scale layer3.1.conv1.weight_fake_quant.zero_point layer3.1.conv2.weight layer3.1.conv2.bias layer3.1.conv2.weight_fake_quant.scale layer3.1.conv2.weight_fake_quant.zero_point layer4.0.conv1.weight layer4.0.conv1.bias layer4.0.conv1.weight_fake_quant.scale layer4.0.conv1.weight_fake_quant.zero_point layer4.0.conv2.weight layer4.0.conv2.bias layer4.0.conv2.weight_fake_quant.scale layer4.0.conv2.weight_fake_quant.zero_point layer4.0.downsample.0.weight layer4.0.downsample.0.bias layer4.0.downsample.0.weight_fake_quant.scale layer4.0.downsample.0.weight_fake_quant.zero_point layer4.1.conv1.weight layer4.1.conv1.bias layer4.1.conv1.weight_fake_quant.scale layer4.1.conv1.weight_fake_quant.zero_point layer4.1.conv2.weight layer4.1.conv2.bias layer4.1.conv2.weight_fake_quant.scale layer4.1.conv2.weight_fake_quant.zero_point fc.weight fc.bias 691
