### ISSUE TITLE
输入输出设置成16bit

### ISSUE THREAD

**Issue by pixel-lt** [ModelTC/MQBench#244]
hi，首尾两层的input 、output 可以设置成16bit吗？要怎么操作呀？

**Comment by wimh966** [comment]
你好，可以在加载量化模型之后，通过找到对应层的observer和quantizer, 给入新的比特，进行初始化。mqbench/observer.py和文件mqbench/fake_quantize/quantize_base.py 会重新定义quant_min, quant_max等参数。
