### ISSUE TITLE
使用convert_deploy导出的onnx进行推理的指标与在训练过程中的指标不一致，要差于训练过程，做了QAT量化导出和非QAT量化导出的实验对比，非QAT量化导出的onnx推理指标正常

### ISSUE THREAD

**Issue by Jim2016713** [ModelTC/MQBench#248]
使用convert_deploy导出的onnx进行推理的指标与在训练过程中的指标不一致，要差于训练过程，做了QAT量化导出和非QAT量化导出，非QAT量化导出的onnx推理指标正常，想请教一下这是什么原因导致的呀

**Comment by Tracin** [comment]
What is the deploy backend?

**Comment by dengxiongshi** [comment]
> 使用convert_deploy导出的onnx进行推理的指标与在训练过程中的指标不一致，要差于训练过程，做了QAT量化导出和非QAT量化导出，非QAT量化导出的onnx推理指标正常，想请教一下这是什么原因导致的呀

@Jim2016713 你好，请问一下解决了嘛👀

**Comment by dengxiongshi** [comment]
> What is the deploy backend?

@Tracin 我用的是tensorrt.
