### ISSUE TITLE
onnx inference

### ISSUE THREAD

**Issue by www516717402** [ModelTC/MQBench#25]
Hello. 
    Finish model translate to onnx-quant, however cant use onnx-runtime to inference. error log `No Op registered for LearnablePerTensorAffine with domain_version of 11`

**Comment by Tracin** [comment]
Onnx model with customed quantized op can not be deployed directly.
If you want to deploy model on onnx-runtime, try backend_type = onnx_qnn.

**Comment by www516717402** [comment]
@Tracin Still get error when i set `BackendType.ONNX_QNN`, trigger code as follows:
[code](https://github.com/ModelTC/MQBench/blob/d1081061726106d7635e31f4f7eb96c5ac1c0e82/mqbench/deploy/deploy_onnx_qnn.py?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L78) comment: op_type=`Mul` not in `FAKE_QUANTIZE_OP`

**Comment by Tracin** [comment]
Nice bug ! Would you mind release your torch model and something to reproduce?

**Comment by www516717402** [comment]
@Tracin This this a bug.
![image](https://user-images.githubusercontent.com/30460509/144578009-2b847f1f-bc9c-4110-8e0c-f8d3a5a5ff53.png)

**Comment by www516717402** [comment]
Code and model from [source](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/models/dense_heads/yolox_head.py)

**Comment by Tracin** [comment]
Something wrong with `symbilic_trace` due to the model definition in MMDet, try use EOD https://github.com/ModelTC/EOD please.

**Comment by www516717402** [comment]
@Tracin Thank you for reply. Please give a example which MMDet not suite for symbilic_trace.

**Comment by Tracin** [comment]
For current specific issue, add `torch.nn.qat.Conv2d` in `module_type_to_quant_input` of `TVMQuantizer` should be fine.

**Comment by www516717402** [comment]
Thanks. I will test EOD for more details.
