### ISSUE TITLE
关于模型中有控制流不能被追踪的问题

### ISSUE THREAD

**Issue by wrxyz** [ModelTC/MQBench#253]
大家的模型里面都没有控制流吗？这个问题是怎么解决的？ raise TraceError('symbolically traced variables cannot be used as inputs to control flow')
torch.fx.proxy.TraceError: symbolically traced variables cannot be used as inputs to control flow

**Comment by Tracin** [comment]
可以手动修改forward来让条件控制流变得确定；实际上trace可以给输入参数，来确定一个想要的控制流。
