### ISSUE TITLE
The accuracy of mqbench QAT is inconsistent with that of running it using SNPE

### ISSUE THREAD

**Issue by theNefelibata** [ModelTC/MQBench#254]
We trained a model using the QAT mode of Mqbench and evaluated it using MQbench. By selecting BackendType.SNPE, the accuracy could reach 85%. When I exported the deploy model and converted it into DLC(https://mqbench.readthedocs.io/en/latest/user_guide/deploy/snpe.html), the accuracy ran on the device was only 80%, What could be the reason?

**Comment by Tracin** [comment]
首先可以在SNPE转换log中，验证MQBench生成了DLC需要的所有tensor range

**Comment by theNefelibata** [comment]
> 首先可以在SNPE转换log中，验证MQBench生成了DLC需要的所有tensor range

如果没有生成呢 有相关的参数可以设置吗
