### ISSUE TITLE
为什么vitis后端每层都量化？

### ISSUE THREAD

**Issue by jeannotes** [ModelTC/MQBench#257]
对于vitis后端，如果当前是一个conv，其实已经对这个conv做了fake convolution，为什么在当前层后面还加一个act quantization，不是重复吗，意义在哪儿

**Comment by Tracin** [comment]
QConv一般只是做了weight的fake quant，输入的fake quant需要插入额外节点

**Comment by jeannotes** [comment]
能再解释详细一点吗，没怎么理解
