### ISSUE TITLE
model.zero_grad() ?

### ISSUE THREAD

**Issue by jeannotes** [ModelTC/MQBench#258]
in     
https://github.com/ModelTC/MQBench/blob/a57f16a80b4af38168706a65fb9e078e105c999f/application/yolov5_example/train.py#L377
          
            if opt.quantize:
                if calibration_flag:
                    if i >= 50:
                        calibration_flag = False
                        model.zero_grad()
                        enable_quantization(model)
                        print('close calibration')
                    else:
                        print('calibration iter{}'.format(i))
                        continue

I am wondering why there is " model.zero_grad() ", what is the purpose?

**Comment by Tracin** [comment]
Calibration stage only for initialize the range (min / max) not for backward, so we can zero_grad().
