### ISSUE TITLE
application/imagenet_example 例子不能执行

### ISSUE THREAD

**Issue by wangshankun** [ModelTC/MQBench#26]
![image](https://user-images.githubusercontent.com/3970271/145179018-71b3fcd2-4944-4b71-ae25-5512c86d2efd.png)

![image](https://user-images.githubusercontent.com/3970271/145179095-6d8fe4a6-916c-48b4-afec-32bc81ed6fa6.png)

**Comment by wangshankun** [comment]
同样的test下面的测试也无法执行，MQBench没安装好吗？
![image](https://user-images.githubusercontent.com/3970271/145182882-05ab9e18-d522-483f-8eb7-7125f566871b.png)

**Comment by Tracin** [comment]
升级一下Mqbench版本吧
torch使用1.8.1

**Comment by wangshankun** [comment]
> 升级一下Mqbench版本吧 torch使用1.8.1
=================================
用的默认分支 main;  torch是1.10.0不行吗？

![image](https://user-images.githubusercontent.com/3970271/145189516-59a835a9-3836-4e5f-a40c-ce82c3637f0d.png)

**Comment by wangshankun** [comment]
切到v0.0.4 tag，
python setup.py install 出来依旧是0.0.2吗？

![image](https://user-images.githubusercontent.com/3970271/145190104-79a5c84b-c921-4838-8c0a-b5e14de6d18b.png)

**Comment by Tracin** [comment]
1.10.0有一些无法兼容的地方,推荐使用用1.8.1

**Comment by wangshankun** [comment]
> 1.10.0有一些无法兼容的地方,推荐使用用1.8.1

切1.8.1一样的问题， 是不是安装readme的安装方法达不到效果呢？
![image](https://user-images.githubusercontent.com/3970271/145191960-5a0fabe9-c0e1-4ca8-a76d-ecbf29d0b121.png)

**Comment by wangshankun** [comment]
用release 0.0.4一样的error
![image](https://user-images.githubusercontent.com/3970271/145192808-4eaa0d6b-d514-4ef9-9b02-34f1ba3be2e0.png)

**Comment by Tracin** [comment]
> 切到v0.0.4 tag， python setup.py install 出来依旧是0.0.2吗？
> 
> ![image](https://user-images.githubusercontent.com/3970271/145190104-79a5c84b-c921-4838-8c0a-b5e14de6d18b.png)

有一点小问题,可以不install, `export PYTHONPATH=$PYTHONPATH:/path_to_quantization/` 来使用
