### ISSUE TITLE
vitis-ai-gpu:1.4.1难以建立，请问有什么可用的镜像吗？

### ISSUE THREAD

**Issue by ranger-wang** [ModelTC/MQBench#260]
vitis-ai已经更新到了3.5版本，用以前的1.4.1的文件创建1.4.1镜像始终失败。请问至少哪个版本的vitis-ai是适配mqbench的？或者有没有现成的镜像可以pull下来？

**Comment by PannenetsF** [comment]
We align the vitis ai backend to the v1.4.1 for now.

And we checked the docker.io, where the vitis' docker image is hosted. The 1.4.1 image is still available and the docker file should work fine. 

You can try some docker.io's mirrors? I can build it successfully.

**Comment by ranger-wang** [comment]
Thank. I make a mistake that I still want to make a vitis-ai-gpu image by vitis-ai's dockerfile and forget that convert don't need gpu……
