### ISSUE TITLE
WARNING

### ISSUE THREAD

**Issue by zfstr** [ModelTC/MQBench#269]
WARNING: The shape inference of ::LearnablePerTensorAffine type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of ::FakeQuantizeLearnablePerchannelAffine type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
how to do

**Comment by Ramezaan7** [comment]
Hello

**Comment by BambooKui** [comment]
请问你问题解决了吗？
