### ISSUE TITLE
atout QAT method

### ISSUE THREAD

**Issue by xiaolonghao** [ModelTC/MQBench#27]
Hello, I am very glad to see that you are making a quantitative library. Recently I read a paper called 'Learnable Companding Quantization for Accurate Low-bit Neural Networks'（LCQ）, the result of this paper is very good, but it cannot be reproduced by itself, so I would like to ask you to reproduce it. If this result can be adopted, it will refresh the ranking, thank you.

**Comment by Tracin** [comment]
We notice there are lots of nonuniform-scheme algos in papers achieve excellent results but are absent in this project, so maybe not LCQ but they are worthy and will be in this project soon.
