### ISSUE TITLE
请问会加入openvino的支持么？

### ISSUE THREAD

**Issue by thb1314** [ModelTC/MQBench#28]
如题，openvino目前已经支持量化，并开源了模型压缩工具库，nncf。支持onnx的量化算子的导入
请问可以考虑加入对openvino int8量化的支持吗？

**Comment by Tracin** [comment]
会的, 已经加入到了计划当中

**Comment by XHPlus** [comment]
Thanks for your contribution! For others to follow, please see: https://github.com/ModelTC/MQBench/pull/40
