### ISSUE TITLE
关于int16量化

### ISSUE THREAD

**Issue by pixel-lt** [ModelTC/MQBench#33]
文档里提到nnie跟qnn支持16bit量化， 实际训练时是否只需要把a_qscheme的bit设置成16即可。

**Comment by Tracin** [comment]
QNN可以, NNIE的INT16量化参数写入需要另外的编码文件,暂未提供,故暂不可写入量化参数,这样会有一定的精度损失.

**Comment by pixel-lt** [comment]
后续有更新计划吗

**Comment by Tracin** [comment]
我们在以往的经验里, 认为INT16一般不会遇到量化精度问题
