### ISSUE TITLE
onnx_qnn convert deploy problems

### ISSUE THREAD

**Issue by pixel-lt** [ModelTC/MQBench#38]
![image](https://user-images.githubusercontent.com/60416830/151335496-13b39337-706b-4e04-990a-ac240565edb0.png)

I'm having a conversion problem  use BackendType.ONNX_QNN. The networks is seems like above,  and the error code is  " op_type=Conv not in FAKE_QUANTIZE_OP"(in fused relu pass), looking forward to a reply

**Comment by pixel-lt** [comment]
when i update mqbench to latest version, there is another error ，''assert _next_node.op_type in self.qlinear_op_type
AssertionError''

**Comment by pixel-lt** [comment]
I look at  the code and found that 'Concat' was not supported.

**Comment by Tracin** [comment]
Any code(especially model definition) to reproduce?

**Comment by pixel-lt** [comment]
> Any code(especially model definition) to reproduce?

I  added 'replace_concat_to_qlinearconcat'  in deploy_onnx_qnn myself， it works.
