### ISSUE TITLE
How do you generate int4 tensorrt engine? 

### ISSUE THREAD

**Issue by pycoco** [ModelTC/MQBench#42]
is there a doc for how to use int4 with tensorrt?

**Comment by XHPlus** [comment]
TensorRT does not support int4 right now.

**Comment by pycoco** [comment]
![clipboard_image_1645169344007](https://user-images.githubusercontent.com/11053628/154637609-049ac2f9-eeb0-4cad-a8c0-8bfe6a25b2de.png)
can you explain a little to me in this TensorRT Leaderboard?

**Comment by XHPlus** [comment]
We apply the same quantization position and scheme as TensorRT and change the bit to 4 to get this accuracy result. This is only to reveal the accuracy potential. As TensorRT has not released support for INT4 inference, the export to TensorRT engine can not be achieved right now.

**Comment by pycoco** [comment]
> We apply the same quantization position and scheme as TensorRT and change the bit to 4 to get this accuracy result. This is only to reveal the accuracy potential. As TensorRT has not released support for INT4 inference, the export to TensorRT engine can not be achieved right now.

Thanks for your generous reply! It is a great work.
