### ISSUE TITLE
no function of prepare_qat_fx_by_platform

### ISSUE THREAD

**Issue by zhixiongzh** [ModelTC/MQBench#48]
Hi,

I can't find the definition of prepare_qat_fx_by_platform, which should be in the library mqbench.prepare_by_platform.

Do you just forget to upload the function?

**Comment by Tracin** [comment]
`prepare_by_platform` for now.

**Comment by zhixiongzh** [comment]
> `prepare_by_platform` for now.

Thank you for the quick response.
In this case, PTQ and QAT use the same function to prepare the model,  then how does the function tell it should be a PTQ or QAT? Only by training or not in the next step?

If possible, can I get a complete example to see how QAT works? I am very interested in the tool, but it seems most of the configuration parameters are not provided/demonstrated.

For example, in `prepare_custom_config_dict`, I can only find out how to set `extra_qconfig_dict`, but no idea and no document to demonstrate what the parameters in `extra_quantizer_dict`, `concrete_args`, and `extra_fuse_dict` look like.

**Comment by Tracin** [comment]
You can find few answers here https://mqbench.readthedocs.io/en/latest/.
We notice the lack of  details , those can be found in source code easily actually.
