### ISSUE TITLE
default quant_min is mismatched with hardware

### ISSUE THREAD

**Issue by zhixiongzh** [ModelTC/MQBench#50]
Hi,

when the bit is 8 and the backend is TensorRT, the default `quant_min` and `quant_max` of `fake_quantizer ` is -128 and 127 separately. But from the document for TensorRT, you mention that

> For weights, [lb, ub] = [-127, 127]. For activations, [lb, ub] = [-128, 127].

is there a conflict here with regard to the weights?

**Comment by Tracin** [comment]
Actually weight can not be -128, since the max abs value will be mapped to 127 / -127, so it is fine. Am I right?

**Comment by zhixiongzh** [comment]
> Actually weight can not be -128, since the max abs value will be mapped to 127 / -127, so it is fine. Am I right?

let's say when we do the QAT, the weight is `-42.24`, and the scale is `0.33`, then after quantization `-42.24/0.33` we get `-128`, and since `-128` is with in the range of `[quant_min, quant_max]`, it won't be cliped.

when we deploy the model with 8 bits and on TensorRT, theoretically the weight is saved as `1000 0001`（two's complement representation）, the scale 0.33 is saved as fp32. 

So here is a conflict, TensorRT only accept -127 for weights, should be `1111 1111` (not two's complement representation I guess?). How MQBench solve the problem here？

**Comment by Tracin** [comment]
`max_bit` is 127 as far as we know. scale = `data_max` / 127.

**Comment by zhixiongzh** [comment]
> `max_bit` is 127 as far as we know. scale = `data_max` / 127.

Thanks for this information！ 

That seems to make more sense. I thought the scale is fixed during training, isn't it? If scale is fixed during training, then the weights could be updated to larger, then after quantization it is also larger than -128.

if not, then the larger number is -127, that is right.

**Comment by Tracin** [comment]
> 

scale can be fixed or not fixed both.
weather it is fixed, the scale exported for deploy will indicate hardware to clip the weight.
this is why pass scale to hardware tool (Tensorrt i.e.) is important.
