### ISSUE TITLE
Question about EMAQuantileObserver

### ISSUE THREAD

**Issue by PuNeal** [ModelTC/MQBench#51]
I am confused about the implementation in the forward method of EMAQuantileObserver:
```
cur_total = 0
clip_value = torch.max(-min_val_cur, max_val_cur)
for i, cnt in enumerate(hist):
    if cur_total + cnt >= self.threshold * x.numel():
        clip_value = (i + 0.5) * (max_val_cur / self.bins)
        break
```
What role does the var `cur_total` play in this code? Should the var `cur_total` be added with `cnt` in each for loop ?
Thank you!

**Comment by Tracin** [comment]
`cur_total` is not updated correctly. A pull requests will be linked to this issue soon.
