### ISSUE TITLE
Example of AdaRound with tensorRT

### ISSUE THREAD

**Issue by luyi404** [ModelTC/MQBench#53]
Thanks for your team's work. Can you post an **example** of **AdaRound** with tensorRT? 
Since the doc[http://mqbench.tech/assets/docs/html/user_guide/PTQ/adaround.html](url) is hard to start and the application example is for the QAT, I am wondering if your team could provide an example for us, it will help us a lot.

**Comment by XHPlus** [comment]
Good suggestion! We will add such an example as soon as possible.

**Comment by luyi404** [comment]
@XHPlus Thank you for the reply. Looking forward to seeing the official examples!

**Comment by zhiwei-dong** [comment]
We add a new example with TRT new explicit mode and Adaround, try later waiting for PR#71 merged.
