### ISSUE TITLE
errors when reproduce adaround results in example/PTQ/ptq.py

### ISSUE THREAD

**Issue by jiangaojie** [ModelTC/MQBench#61]
File "ptq.py", line 69, in <module>
    model = ptq_reconstruction(
  File "/home/xxx/mq/MQBench/mqbench/advanced_ptq.py", line 418, in ptq_reconstruction
    subgraph_reconstruction(subgraph, cached_inps, cached_oups, config)
  File "/home/xxx/mq/MQBench/mqbench/advanced_ptq.py", line 198, in subgraph_reconstruction
    assert USE_LINK or USE_DDP, 'either USE_LINK or USE_DDP should be True'
AssertionError: either USE_LINK or USE_DDP should be True
Thank you very much if you can answer this question

**Comment by luyi404** [comment]
I have the same problem, but I just delete this assert line and manually set the world size = 1 to avoid using distributed training.

**Comment by jiangaojie** [comment]
> I have the same problem, but I just delete this assert line and manually set the world size = 1 to avoid using distributed training.

yes，I did same with you . thanks for your answer
