### ISSUE TITLE
how to use in mmdet build model

### ISSUE THREAD

**Issue by 791136190** [ModelTC/MQBench#63]
when use mmdet build this model, it will like:
object {  
module list aaaa
module list bbb
}
when use prepare_by_platform to trace will get error like: TypeError: 'xxxobject' object does not support indexing

**Comment by zhiwei-dong** [comment]
?

**Comment by Tracin** [comment]
For object detection task, we highly recommand using [EOD](https://github.com/ModelTC/EOD).
Which model do you want to do QAT on ?

**Comment by LMerCy** [comment]
@Tracin Actually we also have requiremetns to integrate mqbench into mmdet, can eod be seen as a good practice?

**Comment by 791136190** [comment]
> For model detection task, we highly recommand using [EOD](https://github.com/ModelTC/EOD). Which model do you want to do QAT on ?

Since we are building our own model with mmdet, it may not be too convenient to use eod.

**Comment by Tracin** [comment]
> @Tracin Actually we also have requiremetns to integrate mqbench into mmdet, can eod be seen as a good practice?

Model in EOD is "trace friendly" it is important for MQBench to do qat.
If you have to use mmdet, a lot modification have to be done.
You have to make the model pass `symbolic_trace` smoothly.

**Comment by Tracin** [comment]
> > For model detection task, we highly recommand using [EOD](https://github.com/ModelTC/EOD). Which model do you want to do QAT on ?
> 
> Since we are building our own model with mmdet, it may not be too convenient to use eod.
If you have to use mmdet, a lot modification have to be done.
You have to make the model pass symbolic_trace smoothly.

**Comment by Tracin** [comment]
> > For model detection task, we highly recommand using [EOD](https://github.com/ModelTC/EOD). Which model do you want to do QAT on ?
> 
> Since we are building our own model with mmdet, it may not be too convenient to use eod.

If you have to use mmdet, a lot modification have to be done.
You have to make the model pass symbolic_trace smoothly.

**Comment by 791136190** [comment]
> > > For model detection task, we highly recommand using [EOD](https://github.com/ModelTC/EOD). Which model do you want to do QAT on ?
> > 
> > 
> > Since we are building our own model with mmdet, it may not be too convenient to use eod.
> 
> If you have to use mmdet, a lot modification have to be done. You have to make the model pass symbolic_trace smoothly.

This is a pity, because we are a chip factory, and we cannot change the training code.

**Comment by www516717402** [comment]
@791136190 
I have done the translate. you can ask when you meet any issue. (sorry for code cant share).

**Comment by www516717402** [comment]
@791136190 
1. `prepare_by_platform` only for model. Cant use mmdet `XXXDetector class`
2. I have done the translate by MQBench-0.04 and MMdet-2.21. you can ask when you meet any issue. (sorry for code cant share).

**Comment by 791136190** [comment]
> @791136190
> 
> 1. `prepare_by_platform` only for model. Cant use mmdet `XXXDetector class`
> 2. I have done the translate by MQBench-0.04 and MMdet-2.21. you can ask when you meet any issue. (sorry for code cant share).

@www516717402 Hello, can I take the liberty to ask how the basic modification process is? need modify the model build?

**Comment by www516717402** [comment]
@791136190 
- Need rebuild Detector and head module. 
- Suggest put calib block before distribute model.
