### ISSUE TITLE
Shufflenet cannot be quantified

### ISSUE THREAD

**Issue by aksenventwo** [ModelTC/MQBench#66]
对 Shufflenet 进行量化时，结果完全错误，具体原因见 https://github.com/pytorch/pytorch/issues/75009

建议对 `torch.fake_quantize_per_tensor_affine` 使用时，对其输入 `X`  替换成 `X.contiguous()`

**Comment by Tracin** [comment]
非常有趣, 有兴趣提供一个PR吗?

**Comment by aksenventwo** [comment]
可以的，但是需要晚一点

**Comment by aksenventwo** [comment]
虽然加 `X.contiguous()` 解决了结果错误的问题，但是我使用 `FixedFakequant` 进行 QAT 目前还是无法恢复 float 精度，LSQ 也试过，同样无法恢复，后端是 SNPE。
