### ISSUE TITLE
error in ptq: RuntimeError: Zero-point must be Int32, Float or Half, found Long

### ISSUE THREAD

**Issue by jiawei-liu1103** [ModelTC/MQBench#77]
When I run ptq.py, I find bug as follow:
`RuntimeError: Zero-point must be Int32, Float or Half, found Long`
Then I go back to source code, I find issue /home/jwliu/MQBench-main/mqbench/fake_quantize/fixed.py in forward()
`X = torch.fake_quantize_per_channel_affine(
  X, self.scale.data, self.zero_point.data.long(),
  self.ch_axis, self.quant_min, self.quant_max)`
Why deliberately set zero_point type to long?
How to solve this problem?

**Comment by Tracin** [comment]
It is because of the version of pytorch.
You can fix it manually.

**Comment by jiawei-liu1103** [comment]
> You can fix it manually.

I can fix it manually in `FixedFakeQuantize` and `AdaRoundFakeQuantize` by setting type to float, but how can I fix it in `QDropFakeQuantize`? 
Thank you for your prompt reply

**Comment by lucasjinreal** [comment]
I have solved and able to save onnx.

However, I want the model size shrink down, but it still stay same as origin.

@Tracin Does there a way to save quantized weights, rather than FakeQuantizePerTensorAffine?

**Comment by Tracin** [comment]
Fixed in #85

**Comment by zhaoxin111** [comment]
Hi，I face the same problem，my torch is 1.10.2
I found the zero point is init with torch.int64
How can I fix the problem?
![image](https://user-images.githubusercontent.com/9295202/187376331-4466ad6e-dc73-4944-9954-7c4bf5eed18b.png)

![image](https://user-images.githubusercontent.com/9295202/187375457-bf93154d-3522-4b4c-87b5-4c66e0701657.png)

Fainally, I set zp as float solve the bug
![image](https://user-images.githubusercontent.com/9295202/187378033-bdee1651-abaa-43c9-95ff-d357e940643c.png)
