### ISSUE TITLE
how to export quantized model to onnx?

### ISSUE THREAD

**Issue by lucasjinreal** [ModelTC/MQBench#78]
how to export quantized model to onnx?
Also, wanna ask, if backend choose tensorrt quantized model, able to deploy on ncnn? (just out of curiosity)

**Comment by Tracin** [comment]
Try backend type ONNX_QNN !

**Comment by lucasjinreal** [comment]
@Tracin thanks, may I ask what's the `QNN` meaning here?

**Comment by Tracin** [comment]
> 

Its one kind of runtime.
Reference: https://github.com/apache/tvm/tree/main/python/tvm/relay/qnn

**Comment by lucasjinreal** [comment]
@Tracin Hi, I looked around the mqbench code. Seems quant doesn't using pytorch inside api: `torch.quantization.quantize_fx.prepare_fx, convert_fx` etc. What's the difference between them?
