### ISSUE TITLE
How to reproduce 4-bit QAT (Section 5.4) results reported in the MQBench paper?

### ISSUE THREAD

**Issue by frankinwi** [ModelTC/MQBench#8]
Can you provide some instructions on reproducing the results in Section 5.4?

**Comment by ALIVE321** [comment]
Sorry for waiting. We've tried to provide a simple script as an imagenet example for 4bit QAT, but it requires many epochs for training, which is hard with no distribution tools. Therefore, we have uploaded configuration files containing key hyperparameters for experiments of 4bit academic setting under 'application/lsq_configs'. You can follow the general QAT instuctions and train it in your own environment (for acceleration).

**Comment by frankinwi** [comment]
Thanks for your generous reply! It is a great work offering a comprehensive study and exemplary case to rethink the model quantization. I'll try to reproduce the results.

Once again, congratulations to MQBench accepted by NIPS 2021.

**Comment by kartikgupta-at-anu** [comment]
Can you please point me to the config files for results reported in the paper? It seems there is no directory named application/lsq_config.

**Comment by frankinwi** [comment]
@kartikgupta-at-anu See #23
