### ISSUE TITLE
Solve the processing of data-dependent API and control flow in the model

### ISSUE THREAD

**Issue by aksenventwo** [ModelTC/MQBench#82]
To solve similar problems：

1. https://github.com/pytorch/pytorch/issues/54602
2. https://github.com/pytorch/pytorch/issues/51803
3. https://github.com/pytorch/pytorch/issues/44851

You can refer to the following modifications https://github.com/pytorch/pytorch/issues/51803#issuecomment-1104634592

I hope to help you.

And hope to add this change @Tracin

**Comment by Tracin** [comment]
Excellent job ! I will try to apply this change.
