### ISSUE TITLE
PTQ KeyError

### ISSUE THREAD

**Issue by ayenuaa** [ModelTC/MQBench#92]
我在调试imagenet_example下的PTQ代码时，尝试使用AdaRound对Resnet18和Mobilenetv2进行后量化，均遇到了KeyError的问题，代码都是MQBench自带的代码，我没有动过。
AdaRound on MBV2:
![image](https://user-images.githubusercontent.com/26295078/167986557-35a86c80-661a-405b-b0f8-4d6b057688a4.png)
AdaRound on ResNet18:
![image](https://user-images.githubusercontent.com/26295078/167986648-3aff5c03-6231-40df-87e1-f8b472e55494.png)

**Comment by PannenetsF** [comment]
ok，我会尽快检查下，可能是支持部分children量化的时候的一些错误



---Original---
From: ***@***.***&gt;
Date: Thu, May 12, 2022 11:33 AM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [ModelTC/MQBench] PTQ KeyError (Issue #92)




 
我在调试imagenet_example下的PTQ代码时，尝试使用AdaRound对Resnet18和Mobilenetv2进行后量化，均遇到了KeyError的问题，代码都是MQBench自带的代码，我没有动过。
 AdaRound on MBV2:
 
 AdaRound on ResNet18:

**Comment by zhiwei-dong** [comment]
It's a bug, temporary try commit 05c915e92d9a53e79e8a84191c0454648ea2e0e4, we are fixing it.

**Comment by ayenuaa** [comment]
谢谢你们的回复

**Comment by PannenetsF** [comment]
> 

https://github.com/ModelTC/MQBench/pull/93 可以尝试下

**Comment by ayenuaa** [comment]
> > 
> 
> #93 可以尝试下

重新pull main分支的代码就可以了吗

**Comment by zhiwei-dong** [comment]
等待这个PR merge进main分支, pull一下就可以了

**Comment by ayenuaa** [comment]
最新反馈：
我按照 @zhiwei-dong 的建议切到了commit 05c915e, 还是会报同样的问题：
![image](https://user-images.githubusercontent.com/26295078/168104839-d9280f3b-bf07-4940-bc91-ecb2f98bb3e0.png)
此外，BRECQ和QDrop也会报KeyError。
然后，我follow了 @PannenetsF 最新commit，由于代码还没合，我是手动替换了advanced_ptq.py文件，还是没有解决这个问题。

**Comment by PannenetsF** [comment]
哦？方便把命令还有log都附上来吗，我在本地跑没问题



---Original---
From: ***@***.***&gt;
Date: Thu, May 12, 2022 22:58 PM
To: ***@***.***&gt;;
Cc: "Yunqian ***@***.******@***.***&gt;;
Subject: Re: [ModelTC/MQBench] PTQ KeyError (Issue #92)




 
最新反馈：
 我按照 @zhiwei-dong 的建议切到了commit 05c915e, 还是会报同样的问题：
 
 此外，BRECQ和QDrop也会报KeyError。
 然后，我follow了 @PannenetsF 最新commit，由于代码还没合，我是手动替换了advanced_ptq.py文件，还是没有解决这个问题。

**Comment by zhiwei-dong** [comment]
重新安装一下mqbench？是不是使用的安装的方式使用的，不是PYTHONPATH

**Comment by ayenuaa** [comment]
可以了 要重新装一下mqbench就OK了 感谢 @zhiwei-dong @PannenetsF 的解答
