### ISSUE TITLE
How to convert "clip_ranges.json" to "calibration.cache" for TensorRT?

### ISSUE THREAD

**Issue by xingyueye** [ModelTC/MQBench#95]
Hi, I've seen that a 'deploy_model.onnx' and a 'clip_ranges.json' exported after quantization for TensorRT backend. But how to convert  the "clip_ranges.json" file  to "calibration.cache" that can be directly used by TensorRT? I have test that the "clip_ranges.json" file could not be recognized by TensorRT with log of 
`[TRT] Calibration table does not match calibrator algorithm type.
`
Hope for your help

**Comment by Tracin** [comment]
You really did a great job to get this question.
You need to set range using TRT apis.
https://github.com/ModelTC/MQBench/blob/main/application/imagenet_example/onnx2trt.py#L60-L65

**Comment by Tracin** [comment]
By the way, you actually can convert clip_ranges.json to cali.cache anyway, if you realize cali.cache is just somekind of  "encoded" clip ranges. Not recommended though.

**Comment by xingyueye** [comment]
Thanks a lot, actually I tests the 'onnx2trt.py' scripts, and It works correctly. But in some cases, you know, when the target hardware is not my working machine, I can only provide the onnx and calibration files, using simple commands (trtexec) to deploy instead of a 'onnx2trt' script. 
I understand the clip_ranges.json and cali.cache  just are different representations, so I wonder if there is a conversion script already implemented to convert json to cache

**Comment by Tracin** [comment]
`struct.unpack('>i', bytes.fromhex(line))[0] / 4096.`
I think its something like this.

**Comment by xingyueye** [comment]
It helps a lot, Thank you
