### ISSUE TITLE
Problems about gpu mem usage, execution efficiency, advanced ptq doc.

### ISSUE THREAD

**Issue by ZhangZhiPku** [ModelTC/MQBench#98]
1. https://mqbench.readthedocs.io/en/latest/user_guide/PTQ/advanced.html 所述的例子不能执行
好像要手动把 quantizer 类型改成 AdaRoundFakeQuantize 才可以，会报错：
Traceback (most recent call last):
  File "/root/workingspace/test_mqbench.py", line 52, in <module>
    model = ptq_reconstruction(model, stacked_tensor, ptq_reconstruction_config)
  File "/root/workingspace/mqbench/advanced_ptq.py", line 669, in ptq_reconstruction
    subgraph_reconstruction(subgraph, cached_inps, cached_oups, config)
  File "/root/workingspace/mqbench/advanced_ptq.py", line 296, in subgraph_reconstruction
    weight_quantizer.init(layer.weight.data, config.round_mode)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1177, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'LearnableFakeQuantize' object has no attribute 'init'
torch 1.8.1 和 torch 1.10.0 都过不去

2. https://mqbench.readthedocs.io/en/latest/user_guide/PTQ/advanced.html 所述的例子不能执行
需要安装 addict 库，而它并不在requirements.txt里面

3. calibration执行效率极低，对比结果可以参考这里
![IYP6 %C5(1N0~VVD3WS8V`P](https://user-images.githubusercontent.com/43309460/168974489-d27839cc-dc9f-4e22-9e1c-136a859ce869.jpg)

4. advanced ptq有显存泄露，每一个block之后显存不断上涨，无法完全释放。

加油兄弟，你们在算法上做了许多有意义的工作，希望你们越做越好。

**Comment by Tracin** [comment]
1. 文档只做了介绍，可运行代码可以参考https://github.com/ModelTC/MQBench/tree/main/application/imagenet_example/PTQ/ptq
2. 整个项目没有用到addict
3. 校准只对Pytorch官方observer做了兼容性扩展，效率方面需要向Pytorch提议，https://github.com/pytorch/pytorch
4. 显存问题暂未发现，对sample里的reconstruction过程循环100次测试未发现明显显存泄漏，可能需要提供更明确的复现例子。

**Comment by ZhangZhiPku** [comment]
class HappyNet(torch.nn.Module):
        def __init__(self) -> None:
            super().__init__()
            self.convs1     = torch.nn.Conv2d(in_channels=3, out_channels=64, kernel_size=7, stride=2)
            self.other_conv = torch.nn.ModuleList([torch.nn.Conv2d(in_channels=64, out_channels=64, kernel_size=3, padding=1) for i in range(128)])
        
        def forward(self, x):
            x = self.convs1(x)
            for conv in self.other_conv:
                x = conv(x)
            return x

量化这个网络，然后输入 watch -n 1 nvidia-smi 即可

这个网络自第二层开始，所有的东西全都一样，也就是说你在执行第二个block与最后一个block的过程中消耗的显存应该是一样的。

**Comment by PannenetsF** [comment]
@ZhangZhiPku 这个小网络样例非常有用，我根据它做了一些调试，发现nvidia-smi的输出**确实**没有怎么降低，torch作为较为成熟的框架，应该内存泄露是可以避免的。找到一篇这样的blog https://discuss.pytorch.org/t/how-to-delete-a-tensor-in-gpu-to-free-up-memory/48879/24 。需要用`torch.cuda.memory_allocated()`来查看占用。
之后用你的网络trace到other_conv_22，按照model.code去执行，最后删除输出节点的tensor，可以看到显存占用和第一个print一致，也就是恢复到仅模型在GPU的样子，所以应该是没有内存泄漏的。
![image](https://user-images.githubusercontent.com/45866836/180774295-b1b1c6a2-6fc4-4b78-bca6-150734bca36c.png)

**Comment by PannenetsF** [comment]
注意到每层tensor大小都一致，我猜测是计算图相关的问题。这个问题也困扰了我很久，希望可以一起解决。

**Comment by PannenetsF** [comment]
可以通过`torch.no_grad`将calib显存限制到约2GB显存，其中bs=64
